### ISSUE TITLE
Can't add key or repo when installing - permission denied

### ISSUE THREAD

**Issue by Ethanol6** [OpenVPN/openvpn3-linux#104]
Following the instructions from the page here: https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux?__cf_chl_tk=ajlvFAXYUXQhSTV.WuU0ProEIUknNRiWEEz8MXvGKLA-1643821240-0-gaNycGzNBr0

The first step fails saying "permission denied"
`curl -fsSL https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/openvpn-repo-pkg-keyring.gpg`

I'm using Linux Mint 20.2

**Comment by schwabe** [comment]
you need to have root rights to write into `/etc/`. Try running `sudo -s` first.

**Comment by Ethanol6** [comment]
I should have mentioned that I did run it with sudo. Would -s make any difference?

**Comment by dsommers** [comment]
Does the "permission denied" come from `curl` when fetching the file ... or when writing the `openvpn-repo-pkg-keyring.gpg` file?

We are only able to to look into issues with the former, not the latter.  The `-s` argument may have an effect for you.

**Comment by schwabe** [comment]
`sudo -s` gives you a shell. As @dsommers said just putting `sudo` in front here will not work as you will need to ensure that the ">" part is actually done with sudo right and not the commands that are being run. So getting a root shell with sudo -s is here the easiest way.

**Comment by Ethanol6** [comment]
sudo -s results in the same. The error is not with `curl` but writing the file. My user is part of the "sudo" group should it be added to root or wheel groups too? If I just use the root user directly will that create a problem? 

I have never had permission issues before just using `sudo`

**Comment by Ethanol6** [comment]
> `sudo -s` gives you a shell. As @dsommers said just putting `sudo` in front here will not work as you will need to ensure that the ">" part is actually done with sudo right and not the commands that are being run. So getting a root shell with sudo -s is here the easiest way.
> 
> ```
> curl -fsSL https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/openvpn-repo-pkg-keyring.gpg
> ```
> 
> would work here

This works as well. It prints out a bunch of junk to standard output but I only need to use sudo with this one.

**Comment by moezbenrebah** [comment]
I have the same issue I ran into the permission denied error, either with sudo or sudo -s:

```
sudo -s curl -fsSL https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub | sudo gpg --dearmor > /etc/apt/trusted.gpg.d/openvpn-repo-pkg-keyring.gpg
bash: /etc/apt/trusted.gpg.d/openvpn-repo-pkg-keyring.gpg: Permission denied
curl: (23) Failed writing body
```
please help me

**Comment by dsommers** [comment]
@moezbenrebah Read this comment very carefully: https://github.com/OpenVPN/openvpn3-linux/issues/104#issuecomment-1028244157
