### ISSUE TITLE
DCO & autoload

### ISSUE THREAD

**Issue by Cherkah** [OpenVPN/openvpn3-linux#106]
i would like to know how to enable DCO if i choose the autolod setting :
- NOK `openvpn3-autoload -c /MY/DIRECTORY **_--dco true_**`
-  nothing about DCO settings in the openvpn-autoload man-page 
                (any parameters in the imported configuration profile)

same question about the "Persistent" parameter

thx

**Comment by dsommers** [comment]
With the v17_beta release, I would rather suggest to not use `openvpn3-autoload` at all.  Instead:

1. Import configuration file: `openvpn3 config-import --persistent --config CONFIG_FILE --name CONFIG_NAME`
2. Set the DCO flag: `openvpn3 config-manage --config CONFIG_NAME --dco true`
3. Start the VPN session.  This can be done in more ways:
  a) Ad-hoc start: `openvpn3 session-start --config CONFIG_NAME`
  b) Via systemd: If you imported the configuration file as a non-root user, run following command first:
       `openvpn3 config-acl --config CONFIG_NAME --grant root --transfer-owner-session true --show`.
       Then as `root` run:  `systemctl start openvpn3-session@CONFIG_NAME`
       To always start this session during boot:  `systemctl enable openvpn3-session@CONFIG_NAME`

**Comment by Cherkah** [comment]
thanks for what your recommendation.
until now my "autoload" config is working well hence the following:
- this procedure is relative to the v17, what about the next versions?
- is it a problem of security or performance.

extra: 
when can we expect a first definitive version?

**Comment by Cherkah** [comment]
i've tried what you 've indicated but i am blocked at the step 3)b.

systemctl status openvpn3-session@vpn3_bruxelles_tcp.service
`systemctl status openvpn3-session@vpn3_bruxelles_tcp.service:
XXX systemd[1]: Starting OpenVPN 3 Linux - VPN session for vpn3_bruxelles_tcp...
XXX openvpn3-systemd[85498]: Traceback (most recent call last):
XXX openvpn3-systemd[85498]:   File "/usr/libexec/openvpn3-linux/openvpn3-systemd", line 35, in <module>
XXX openvpn3-systemd[85498]:     import systemd.daemon
XXX openvpn3-systemd[85498]: ModuleNotFoundError: No module named 'systemd'
XXX systemd[1]: openvpn3-session@vpn3_bruxelles_tcp.service: Main process exited, code=exited, status=1/FAILURE
XXX systemd[1]: openvpn3-session@vpn3_bruxelles_tcp.service: Failed with result 'exit-code'.
XXX systemd[1]: Failed to start OpenVPN 3 Linux - VPN session for vpn3_bruxelles_tcp.`

OS: Manjaro
systemd V. 250.3-2

**Comment by dsommers** [comment]
You seem to be missing the `python3-systemd` package.  More upstream details: https://github.com/systemd/python-systemd.

We might miss a dependency in our own packaging, but Manjaro is also not a distribution we target explicitly.

**Comment by dsommers** [comment]
> thanks for what your recommendation. until now my "autoload" config is working well hence the following:
> 
>    * this procedure is relative to the v17, what about the next versions?

The `openvpn3-autoload` was intended as a quick solution until we have something better.  The systemd integration is the main goal.  The `openvpn3-autoload` was added before we had full support for persistent configuration files, and we needed a way to load configuration files in an automated way.

>    * is it a problem of security or performance.

The `openvpn3-autoload` is very simplistic.  And if you run it multiple times, you'll end up with duplicated configuration files, if auto-start of sessions is enabled, they will also start multiple times causing all kinds of odd behavior on the system.  The core design of it was "run only once".

The `openvpn3-systemd` integration builds on the persistent configurations, which gives a more unified way to handle configuration profile management (via `openvpn3 config-manage` and `openvpn3 config-acl`).  And systemd is pulled into manage running VPN sessions, which can also be cross-managed via `openvpn3 session-manage`.  So a session started via `systemctl` can be stopped via `openvpn3 session-manage --disconnect` and systemd handles this correct.

The `openvpn3-systemd` implementation will be further enhanced as well, to also better catch if a session is already running with the same config file.  So it will reflect the current status even better.

> extra: when can we expect a first definitive version?

When it's ready.  But hopefully later this year.  In a release not too far away (2-3 releases perhaps) we will switch the OpenVPN 3 Core library version from the current development branch to a release branch.  Then we will see how that works out over a few releases.  And we will iron out bugs appearing.  We are not planning any big new features in the current code base until we have a stable release out, we focus now on stabilization and bug fixes.  Missing features required to achieve stabilization or resolve bugs might happen, but we generally try to avoid that in the current phase.

There are some outstanding issues we want to resolve, but these issues should not be too intrusive to the overall stability.

**Comment by dsommers** [comment]
If you switch to use the new systemd `openvpn3-sessions@.service` approach, when you enable that (`systemctl enable ...`), it will start the session automatically during boot.  In this case the `openvpn3-autoload.service` should be disabled (`systemctl disable openvpn3-autoload.service`).
