### ISSUE TITLE
Cross-Compilation in different platforms

### ISSUE THREAD

**Issue by katakissof** [OpenVPN/openvpn3-linux#107]
Hi can you provide me instructions of how to cross compile the openvpn3 in different platforms.

It would be very helpful to be something similar with this:

https://paguilar.org/?p=303 

Thanks in advance

**Comment by dsommers** [comment]
Did you read the [README.md](https://github.com/OpenVPN/openvpn3-linux/blob/master/README.md#how-to-build-openvpn3-linux-locally) file?

It's a standard autotools based project, so cross-compiling should work as with any other autotools based project (ie. using `--target`).  Only 64-bit architectures are currently supported.
