### ISSUE TITLE
compile error - sys/capability.h not found

### ISSUE THREAD

**Issue by cryptophd27** [OpenVPN/openvpn3-linux#108]
Hi all, while compiling on Ubuntu 20.04 i get the following error. 

```
/home/user/O3/core/test/unittests/test_sitnl.cpp:22:10: fatal error: sys/capability.h: No such file or directory
   22 | #include <sys/capability.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
any ideas on how to resolve. Anybody had same problem?
Thanks!

**Comment by dsommers** [comment]
Sounds like you're missing the libcap development heards.  Most likely `libcap-dev` or `libcap-devel`, depending on distro.

But are you compiling the openvpn3-linux client or doing a build of the [OpenVPN 3 Core library](https://github.com/OpenVPN/openvpn3/)'s reference implementations and unit tests?
