### ISSUE TITLE
Port Override Requires Int, but Config Manager Requires Boolen or String for Overrides

### ISSUE THREAD

**Issue by beardman2019** [OpenVPN/openvpn3-linux#11]
I was trying to use the port override in a .autoload file. Using any integer results in the error message, "Unsupported override data type:  i." This is true even if I quote the integer.  Escaping the quotes (i.e. trying to force the string) errors out because an int is required.

configmgr.hpp OverrideValue set_override function only accepts string and boolean g_types.  I would submit a pull request, but I haven't quite used github enough to be comfortable doing so.

**Comment by dsommers** [comment]
Ouch, this is an oversight during a refactoring we did a while ago; most likely related to commit 7938ba72b93d7ec829 - or some of the related ones to this one.  Thanks for reporting this issue!

If you have a patch for it, please send it to the public mailing lists, I generally don't like GitHub pull-requests (who knows how easy it is to follow the patch review discussion in 10-15 years if that would be needed; mailing lists are decentralized - github is centralized) - but I may accept really simple fixes via pull-requests if they appear.  The mailing list to use is already described in the [README.md](https://github.com/OpenVPN/openvpn3-linux#contribution) (in the _contribution_ section)

**Comment by dsommers** [comment]
This issue should now be fixed with commit 67162a85919508f0c98e59f6.
