### ISSUE TITLE
Does any plans to add support for Ubuntu 21.10?

### ISSUE THREAD

**Issue by heckad** [OpenVPN/openvpn3-linux#112]
On [wiki page](https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux) the latest supported Ubuntu release is 21.04. It's been 3 months since the release of 21.10. When can we expect the repository to be added? 
I would be happy even with approximate dates. Thank you.

**Comment by dsommers** [comment]
Can you try to use this apt list file?  https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-impish.list
We haven't added it to the fully supported releases yet, so consider this a testing release.

**Comment by heckad** [comment]
Oh, works. Thank you very much!
