### ISSUE TITLE
where is the front end?

### ISSUE THREAD

**Issue by DanTaranis** [OpenVPN/openvpn3-linux#115]
under the front end section you supply cli code?
where is the front end like in windows and mac?

**Comment by dsommers** [comment]
Currently, openpvn3-linux only provides a command line interfaces (`openvpn3`, `openvpn2` and the `openvpn3-session@.service` unit file) as the front-ends.

We do have NetworkManager integration on our TODO list (#46), and it is possible to write other front-ends as well without needing to dive too much into the lower level OpenVPN integration, as the OpenVPN 3 Linux project provides services accessible via D-Bus to manage configuration profiles and VPN sessions.  And it can be written in any language with a D-Bus integration.

**Comment by dsommers** [comment]
JFTR, this was closed as it is a duplicate of #46, #105 and your prior issue ticket #111.
