### ISSUE TITLE
** ERROR ** 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by dangerfish96** [OpenVPN/openvpn3-linux#12]
When I use the command `openvpn2 --config client.ovpn --client` I get the error
** ERROR ** 'NoneType' object is not subscriptable
It works with openvpn3.

client.ovpn:
```
dev tun
tls-client
remote [IP] 1194
redirect-gateway def1
dhcp-option DNS 1.1.1.1
pull
ca ca.crt
comp-lzo
reneg-sec 0
auth-user-pass 
```

**Comment by dsommers** [comment]
Sorry for the long delay, but I've been out of office for some days.  And thanks for the report.  This should be fixed now in commit 87aa4f1c8399fd8a549da.
