### ISSUE TITLE
How to offline deploy openvpn3-linux

### ISSUE THREAD

**Issue by Alceatraz** [OpenVPN/openvpn3-linux#120]
Hello, And:

I have already read this manual `https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux`, But soon I realized there is no deb/rpm  package download. And the official repo dose not support file-index. And I was try some common name like ls-lR.gz but they all return 404.

So how do I deploy offline ? Or  where can I download openvpn3-linux.deb/rpm

**Comment by flichtenheld** [comment]
You are correct that there is no direct download link and the repo currently doesn't support directory indexes. We should probably discuss whether that could easily be added. For now the easiest way is to setup the repository on a machine with internet access and then download the packages with `apt download`.

If you really want to download them manually that would be more involved: You would need to download the Packages file under `https://swupdate.openvpn.net/community/openvpn3/repos/dists/<dist>/main/binary-amd64/Packages.gz` and then look for the packages you need and then use the `Filename` field to construct the download links as `https://swupdate.openvpn.net/community/openvpn3/repos/<Filename>`

**Comment by Alceatraz** [comment]
> You are correct that there is no direct download link and the repo currently doesn't support directory indexes. We should probably discuss whether that could easily be added. For now the easiest way is to setup the repository on a machine with internet access and then download the packages with `apt download`.
> 
> If you really want to download them manually that would be more involved: You would need to download the Packages file under `https://swupdate.openvpn.net/community/openvpn3/repos/dists/<dist>/main/binary-amd64/Packages.gz` and then look for the packages you need and then use the `Filename` field to construct the download links as `https://swupdate.openvpn.net/community/openvpn3/repos/<Filename>`

Thanks, `apt download` solve this problem. I success deploy by apt on another offline machine.
