### ISSUE TITLE
Arch Linux - /etc/resolv.conf getting overwritten

### ISSUE THREAD

**Issue by sant527** [OpenVPN/openvpn3-linux#121]
I am starting openvpn connection using

```
openvpn3 session-start --config client.ovpn
```

but the /etc/resolv.conf is not getting changed with the new dns entries from openvpn

```
# Generated by dhcpcd from wlan0.dhcp, wlan0.dhcp6
# /etc/resolv.conf.head can replace this line
nameserver 192.168.55.1
nameserver fe80::1%wlan0
# /etc/resolv.conf.tail can replace this line
```
it should be Generated by OpenVPN 3 Linux

```
#
# Generated by OpenVPN 3 Linux (NetCfg::DNS::ResolvConfFile)
# Last updated: 2022-05-22 17:49:09 
#

# OpenVPN defined name servers
nameserver 10.0.0.2

# System defined name servers
nameserver 192.168.55.1
nameserver fe80::1%wlan0

```

something like above

what to do.

In one of my other pc it works well. the /etc/resolv.conf also gets changed

**Comment by dsommers** [comment]
Which Linux distribution and version are you running?  More recent OpenVPN 3 Linux releases will use `systemd-resolved` by default if it is expected that the distribution ships with that enabled by default.  Currently that is for all supported Fedora releases and Ubuntu 20.04 and newer.

**Comment by sant527** [comment]
I am using archlinux and installed it as 

```
yay -S openvpn3
```

```
  $ openvpn3 version
OpenVPN 3/Linux git:makepkg:079e9da7f66f5cca+ (openvpn3)
OpenVPN core 3.git:HEAD:7765540e linux x86_64 64-bit
Copyright (C) 2012-2020 OpenVPN Inc. All rights reserved.
```

I am using latest archlinux os.

what shold i do to update the resolv.conf with the dns provided by openvpn


I have another archos, its bit old. but same version of openvpn3 is installed. but there the resolve.conf get updated

**Comment by dsommers** [comment]
We don't have official Arch Linux support yet.  But the Arch guys are doing a reasonably decent job.  I don't know how the DNS resolver settings are handled on Arch, as that seems to do different things than other `systemd-resolved` enabled systems do.

Your `/etc/resolv.conf` says:
```
# Generated by dhcpcd from wlan0.dhcp, wlan0.dhcp6
# /etc/resolv.conf.head can replace this line
nameserver 192.168.55.1
nameserver fe80::1%wlan0
```

While other systems typically have lines like the ones below:
```
# This file is managed by man:systemd-resolved(8). Do not edit.
[....]
nameserver 127.0.0.53
```

The `/etc/resolv.conf` is also a symlink to `/run/systemd/resolve/stub-resolv.conf`.

So there is more to your setup than just systemd-resolved.

Normally, to make OpenVPN 3 Linux use `systemd-resolved`, you need stop all VPN sessions.  Then run this command line as `root`:

    # openvpn3-admin netcfg-service --config-set systemd-resolved true

Finally, `kill -INT` all the `openvpn3-service-*` processes (and in particular `openvpn3-service-netcfg` in this case).  This should override the default configuration of using `/etc/resolv.conf`.

I see a remark in your `resolv.conf` file, which I don't grasp right now ...

     # /etc/resolv.conf.tail can replace this line

If that means that `/etc/resolv.conf.tail` can be used by other applications - you can also tell `openvpn3-service-netcfg` to use such a file instead:

    # openvpn3-admin netcfg-service --config-unset systemd-resolved
    # openvpn3-admin netcfg-service --config-set resolv-conf /etc/resolv.conf.tail

or use another filename which matches better what Arch Linux expects.

If there are any Arch Linux package maintainers who can elaborate more on how that distro handles these things, I'm willing to discuss including upstream changes to detect Arch Linux and do the right thing out-of-the-box.  Including adding native support for other ways to configure the DNS resolver.

**Comment by sant527** [comment]
thanks a lot.  what i found is even if i manually add something to resolv.conf, after 5 seconds it getting override

only option is to set the resolv.cong.head or tail

but after closing the connection we have to remove them.

**Comment by dsommers** [comment]
As this seems to be resolved, I'm closing this issue.

Just a closing comment on the `openvpn3-admin netcfg-service` suggestion above, using `/etc/resolv.conf.head`.  With this setting, `openvpn3-service-netcfg`  will automatically preserve and restore the `resolv.conf.head` file when the VPN sessions starts and disconnects.

Feel free to point any related Arch Linux bug tracking to this ticket, if that can help improving the Arch Linux packaging and the out-of-box experience with OpenVPN 3 Linux.

**Comment by TwIsL** [comment]
On my Manjaro distro a have issue with DNS resolver

```
$ openvpn3 log --log-level 6 --config <my_config_file>
Waiting for session to start ... Done
Attaching to session /net/openvpn/v3/sessions/01b9f9efs8230s43e4s9a59s34685e58388a
2024-06-10 14:01:19  [STATUS] Connection, Configuration OK: config_path=/net/openvpn/v3/configuration/56294862x4ec6x4d62xa76axa7bfaacefd0c
2024-06-10 14:01:19  Client INFO: Starting connection
2024-06-10 14:01:19  [STATUS] Connection, Client connecting
2024-06-10 14:01:19  Client INFO: Connecting
2024-06-10 14:01:19  [STATUS] Connection, Client connecting
2024-06-10 14:01:20  Client !! CRITICAL !!: Failed changing DNS Scope: No DNS resolver configured
2024-06-10 14:01:20  Client INFO: Connected: <myserver> (<server_Ip>) via /TCP on tun/10.2.1.18/ gw=[10.2.1.1/] mtu=1500
2024-06-10 14:01:20  [STATUS] Connection, Client connected
```
How can i configure DNS resolver in my system? Or how can i configure openvpn instead?
