### ISSUE TITLE
RHEL 9 OPENVPN Installation failed

### ISSUE THREAD

**Issue by fazalmf** [OpenVPN/openvpn3-linux#125]
Unable to install OPENVPN client  on RHEL 9.

**Comment by dsommers** [comment]
Yes, we have recently discovered that the build environment used for the Fedora Copr was built with the wrong buildroot.  And that causes some side-effects.

I've kicked off an additional build using the Fedora Koji builders; this should work better.  But you need to download the RPMs manually for now, until we get the Copr builds properly fixed.

https://koji.fedoraproject.org/koji/taskinfo?taskID=88073288  (x86_64)
https://koji.fedoraproject.org/koji/taskinfo?taskID=88073286  (ppc64le)
https://koji.fedoraproject.org/koji/taskinfo?taskID=88073285  (aarch64)

**Comment by fazalmf** [comment]
getting following errors

[root@fazalrhel ~]# rpm -ivh openvpn3-18-1.beta1.el9.x86_64.rpm
error: Failed dependencies:
        jsoncpp is needed by openvpn3-18-1.beta1.el9.x86_64
        libjsoncpp.so.25()(64bit) is needed by openvpn3-18-1.beta1.el9.x86_64
        libprotobuf.so.25()(64bit) is needed by openvpn3-18-1.beta1.el9.x86_64
        libtinyxml2.so.9()(64bit) is needed by openvpn3-18-1.beta1.el9.x86_64
        lz4 is needed by openvpn3-18-1.beta1.el9.x86_64
        openvpn3-selinux >= 18-1.beta1.el9 is needed by openvpn3-18-1.beta1.el9.x86_64
        protobuf is needed by openvpn3-18-1.beta1.el9.x86_64
[root@fazalrhel ~]# wget https://kojipkgs.fedoraproject.org//work/tasks/3288/88073288/openvpn3-client-18-1.beta1.el9.x86_64.rpm
--2022-06-10 11:45:45--  https://kojipkgs.fedoraproject.org//work/tasks/3288/88073288/openvpn3-client-18-1.beta1.el9.x86_64.rpm
Resolving kojipkgs.fedoraproject.org (kojipkgs.fedoraproject.org)... 38.145.60.20, 38.145.60.21
Connecting to kojipkgs.fedoraproject.org (kojipkgs.fedoraproject.org)|38.145.60.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 774021 (756K) [application/x-rpm]
Saving to: ‘openvpn3-client-18-1.beta1.el9.x86_64.rpm’

[root@fazalrhel ~]# rpm -ivh openvpn3-client-18-1.beta1.el9.x86_64.rpm
error: Failed dependencies:
        libjsoncpp.so.25()(64bit) is needed by openvpn3-client-18-1.beta1.el9.x86_64
        libprotobuf.so.25()(64bit) is needed by openvpn3-client-18-1.beta1.el9.x86_64
        openvpn3(x86-64) = 18-1.beta1.el9 is needed by openvpn3-client-18-1.beta1.el9.x86_64

**Comment by fazalmf** [comment]
![image](https://user-images.githubusercontent.com/17859524/173002972-3634f7ca-1750-46a1-8943-5d062c973a56.png)

**Comment by dsommers** [comment]
You have not installed the Fedora EPEL-9 repository.  Instructions here https://docs.fedoraproject.org/en-US/epel/#_el9

The Fedora Copr build should now be fixed as well, so using `yum copr enable dsommers/openvpn3` it should now be possible to install directly from the Copr repository.  More instructions here: https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux

**Comment by dsommers** [comment]
I have run multiple successful tests on RHEL-9 with the `openvpn3-client` and `kmod-ovpn-dco` package using the `dsommers/openvpn3` Copr repository.  Closing this issue.

**Comment by fazalmf** [comment]
community instruction  worked well  thanks your support .
