### ISSUE TITLE
Missing Routes

### ISSUE THREAD

**Issue by scrouchman** [OpenVPN/openvpn3-linux#132]
I've been using this openvpn config against version 2.4 for years, however when I use V3 not all my routes are added.
The server pushes routes and the client adds its own, but I don't get a consistent set from either of them.
I've tried starting the session with a log level of 6 but it adds basically nothing other than saying it connected.

```
Attaching to session /net/openvpn/v3/sessions/00d9f37bs2549s4f94sa23esef595952f174
2022-07-01 15:56:13 [STATUS] Connection, Configuration OK: config_path=/net/openvpn/v3/configuration/957b3c9ax8edex4a2cx9975x363b1134f278
2022-07-01 15:56:13 Client INFO: Starting connection
2022-07-01 15:56:13 [STATUS] Connection, Client connecting
2022-07-01 15:56:14 Client VERB1: Waiting for server response
2022-07-01 15:56:14 Client INFO: Connecting
2022-07-01 15:56:14 [STATUS] Connection, Client connecting
2022-07-01 15:56:15 Client INFO: Connected: scrouchman@devenvs.livedrive.com:1194 (185.21.110.193) via /UDPv4 on tun/10.120.75.4/ gw=[10.120.75.1/]
2022-07-01 15:56:15 [STATUS] Connection, Client connected
```

If I use the openvpn2 wrapper I get
`
** ERROR ** /usr/bin/openvpn2: error: unrecognized arguments: --pull-filter ignore
`

Can I get an actual trace output from the openvpn3 library so I can see what routes its adding?

**Comment by dsommers** [comment]
First, when you get that error, the `openvpn2` wrapper doesn't really try to connect yet.  So nothing really happening here.  The OpenVPN 3 Python module is lacking support for some options; I'll put that on the plan for the v19_beta release.

So to the logging issue.  With the v18_beta release, the whole logging implementation got a serious (and needed) overhaul.  I would recommend you to try this:

      $ openvpn3 config-import --persistent --config /path/to/config/file.ovpn --name myvpn
      $ openvpn3 config-manage --show --config myvpn --log-level 6

This has the advantage of importing the configuration profile directly into the configuration manager, not going via the Python module at all.  The OpenVPN 3 Core library which is used under the hood should have support for `--pull-filter`.

To get the logging - in one terminal run:

     $ openvpn3 log --config myvpn

In another terminal you start the VPN session like this:

     $ openvpn3 session-start --config myvpn

If that doesn't give you more verbose logging, try increasing the log level in the logger service.  As root, run this command:

     # openvpn3-admin log-service --log-level 6

I have on my agenda to simplify the `openvpn3 log` and `openvpn3 session-start`  commands.  But I'm not there yet.

**Comment by scrouchman** [comment]
So, the logging I needed came from the last command for the openvpn3-admin logging. That spat out this very helpful error
`
"tun_prop_route_error: route destinations other than vpn_gateway or net_gateway are not supported"
`
Changed my config to remove the explicit gateway from the route pushes and they're all there now. Thanks for the help
