### ISSUE TITLE
v13_beta cannot start session on WSL2

### ISSUE THREAD

**Issue by ShahrinNakkhatra-optimizely** [OpenVPN/openvpn3-linux#134]
Hi, I have downgraded to v13_beta as I was getting errors while trying to import (.ovpn) config profile on v18_beta.
Current version is: openvpn3=13~beta-1+focal

I'm using ubuntu on WSL2. Now after I import the config, I'm still getting asked for username and password. And even though I'm providing it, I'm getting errors. When I installed on windows, it took the username automatically from the config profile. Not sure why I'm having to do this on WSL2 Ubuntu.

Also, I was not connected to OpenVPN on windows while trying to do this on WSL2 Ubuntu. My resolv.conf has one line only which is nameserver 1.1.1.1 and in wsl.conf generateResolvconf is set to false.

```
nakkhatra@ShNak220:~/code$ openvpn3 config-import --config profile-1171.ovpn –persistent
Configuration imported.  Configuration path: /net/openvpn/v3/configuration/** {Config path was here} **
nakkhatra@ShNak220:~/code$ openvpn3 configs-list
Configuration path
Imported                        Last used                 Used
Name                                                      Owner
------------------------------------------------------------------------------
/net/openvpn/v3/configuration/** {Config path was here} **
Thu Jul 14 17:02:41 2022                                  0
profile-1171.ovpn                                         nakkhatra
------------------------------------------------------------------------------
nakkhatra@ShNak220:~/code$ openvpn3 session-start --config profile-1171.ovpn
Using pre-loaded configuration profile 'profile-1171.ovpn'
Session path: /net/openvpn/v3/sessions/dfdbede2se899s4300s882ds4ce85deb1ee8
Auth User name: **Used my user name from the config file's OVPN_ACCESS_SERVER_USERNAME
Auth Password: **Used the same password that I used for connecting on windows
session-start: ** ERROR ** Failed to connect: Connection, Client reconnect
```

**Comment by dsommers** [comment]
Please, can you provide more log details?  Before you run another test, as root, run

    # openvpn3-admin log-service --log-level 6

Then set the same log level for the VPN config:

    $ openvpn3 config-manage --show --config profile-1171.ovpn --log-level 6

Then you can try connecting and extract log events using:

    # journalctl --since 10m SYSLOG_IDENTIFIER=net.openvpn.v3.log

If that doesn't give you anything, try changing the `SYSLOG_IDENTIFIER` to use `openvpn3-service-logger` instead.

**Comment by ShahrinNakkhatra-optimizely** [comment]
This is what I'm getting. Btw I changed the profile meanwhile. It works properly on my windows installation of openvpn.
![image](https://user-images.githubusercontent.com/107552089/184885625-c800cac3-754e-401b-a812-a059189eece3.png)

**Comment by ShahrinNakkhatra-optimizely** [comment]
@dsommers 
nakkhatra@ShNak220:~$ openvpn3 session-start --config-path /net/openvpn/v3/configuration/2283a4b2x1819x4681xbd65xdc11fddf26ab
Session path: /net/openvpn/v3/sessions/1d0da918sb91es4482s8a3cs22e0f31b87e7
session-start: ** ERROR ** Failed to start new session: Failed calling D-Bus method Ready: GDBus.Error:net.openvpn.v3.sessions.error: Backend VPN process has died.  Session is no longer valid.

**Comment by dsommers** [comment]
Sorry, the `journalctl` command was slightly wrong ... it should say `--since -10m` ... please have a look at those logs.  Also ensure `openvpn3-admin log-service --log-level 6` is set too.

**Comment by ShahrinNakkhatra-optimizely** [comment]
@dsommers Meanwhile I uninstalled openvpn and reinstalled before sending you the journalctl reports for the first time. Seems like the errors I get when I use session start is different this time and not even asking for my username/password either.

Also tried it with the old profile-1171.ovpn. Same thing. Can't find any journal file either.

**Comment by dsommers** [comment]
Did you also read this line in a prior comment?

> If that doesn't give you anything, try changing the SYSLOG_IDENTIFIER to use openvpn3-service-logger instead.

**Comment by dsommers** [comment]
Oh wait .... it seems `systemd-journald` isn't configured or running.

Can you check for other syslog files in `/var/log/` and see if you find traces of `openvpn3-service` processes there?

**Comment by ShahrinNakkhatra-optimizely** [comment]
Using SYSLOG_IDENTIFIER=openvpn3-service-logger also returned the same. 

```
nakkhatra@ShNak220:~$ grep openvpn3 /var/log/...
grep: /var/log/...: No such file or directory
nakkhatra@ShNak220:/var/log$ ls -al
total 528
drwxrwxr-x   9 root      syslog            4096 Aug 18 12:10 .
drwxr-xr-x  13 root      root              4096 Mar 25 03:42 ..
-rw-r--r--   1 root      root             19676 Aug 18 12:33 alternatives.log
drwxr-xr-x   2 root      root              4096 Aug 18 12:33 apt
-rw-rw----   1 root      utmp                 0 Mar 25 03:42 btmp
drwxr-xr-x   2 root      root              4096 Feb  8  2022 dist-upgrade
-rw-r--r--   1 root      root            458308 Aug 18 12:33 dpkg.log
-rw-r--r--   1 root      root              3341 Aug 18 12:10 fontconfig.log
drwxr-xr-x   2 root      root              4096 Jul 12  2021 gdm3
drwxr-sr-x+  2 root      systemd-journal   4096 Mar 25 03:40 journal
drwxr-xr-x   2 landscape landscape         4096 Jul 13 15:45 landscape
-rw-rw-r--   1 root      utmp            292292 Aug 18 12:11 lastlog
drwx------   2 root      root              4096 Jul 24 17:53 private
-rw-r--r--   1 root      root                 0 Jul 24 17:53 ubuntu-advantage.log
drwxr-x---   2 root      adm               4096 Jul 21  2020 unattended-upgrades
-rw-r--r--   1 root      root                26 Aug 14 15:03 upgrade-policy-changed.log
-rw-rw-r--   1 root      utmp                 0 Mar 25 03:42 wtmp
```

**Comment by ShahrinNakkhatra-optimizely** [comment]
```
nakkhatra@ShNak220:/var/log$ ls -al /var/log/journal/
total 8
drwxr-sr-x+ 2 root systemd-journal 4096 Mar 25 03:40 .
drwxrwxr-x  9 root syslog          4096 Aug 18 12:10 ..
```

**Comment by ShahrinNakkhatra-optimizely** [comment]
@dsommers Please let me know if I should make any changes to ```/etc/systemd/journald.conf``` file

**Comment by dsommers** [comment]
You seem to not run neither any syslog service nor systemd-journald.  In this case, it might be easier/quicker to just remove the `--syslog` argument and add `--log-file /var/log/openvpn3.log` to the `openvpn3-service-logger` command line found in `/usr/share/dbus-1/system-services/net.openvpn.v3.log.service`.

**Comment by dsommers** [comment]
Closing due to no further responses.  WSL2 support is not something being actively targeted.  If that changes in the future, we will ensure we have documentation how to do that correctly.
