### ISSUE TITLE
DNS servers are overwritten on macOS Monterey 12.5

### ISSUE THREAD

**Issue by trszdev** [OpenVPN/openvpn3-linux#141]
OpenVpn connect Version 3.3.5 (4310)

dns servers being overwritten with some default dns server like 192.168.3.1

**Comment by dsommers** [comment]
Please report this issue here: https://support.openvpn.com/hc/en-us

This issue tracker is about **OpenVPN 3 *Linux***.  It does not provide a client implementation for macOS.
