### ISSUE TITLE
error:140AB18E

### ISSUE THREAD

**Issue by XcenNoN** [OpenVPN/openvpn3-linux#144]
Hello, there was a problem connecting to the server.

Error:
OpenSSL: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak

Perhaps the problem is the absence of any parameter in the .ovpn file

**Comment by schwabe** [comment]
This means your CA/certificate use weak signatures that modern OpenSSL versions no longer support.  You would need 
tls-cert-profile insecure for your VPN or fix the CA/certificates (see also https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-config-manage.1.rst)
