### ISSUE TITLE
openvpn3-service-logger not starting due to missing log-service.json file

### ISSUE THREAD

**Issue by dsommers** [OpenVPN/openvpn3-linux#147]
_Originally posted by @gforsyth in https://github.com/OpenVPN/openvpn3-linux/issues/142#issuecomment-1249411621_

----

I just ran into this issue -- spelunking around in `journalctl --since today -u dbus` I ran into an error message 

```
Sep 16 10:02:04 stravaig net.openvpn.v3.log[4130]: Failed parsing configuration file: /var/lib/openvpn3/log-service.json
```

I created an empty file called `log-service.json` at that location and then it started up without issue.

This was on Arch, using `openvpn3` built from the AUR

```
openvpn3-admin version --services
OpenVPN 3 D-Bus services:

  - Client backend starter service
     openvpn3-service-backendstart: git:makepkg:848140a8d539a2f7

  - Configuration Service
     openvpn3-service-configmgr:    git:makepkg:848140a8d539a2f7

  - Log Service
     openvpn3-service-logger:       git:makepkg:848140a8d539a2f7

  - Network Configuration Service
     openvpn3-service-netcfg:       git:makepkg:848140a8d539a2f7

  - Session Manager Service
     openvpn3-service-sessionmgr:   git:makepkg:848140a8d539a2f7
```

**Comment by dsommers** [comment]
I have just pushed out a fix for this issue; see commit 0d77441dd7346a943b7e626e18bbd29fb8df0505 for more details.

From the git reference in your `openvpn3 version` output, it looks like you're building from the git master branch. So thanks a lot for testing and catching this issue!

**Comment by gforsyth** [comment]
Working on a recent rebuild -- thanks for the fix!

**Comment by dsommers** [comment]
This has been resolved in the [v19_beta](https://github.com/OpenVPN/openvpn3-linux/releases/tag/v19_beta) release.
