### ISSUE TITLE
My config is getting deleted after a reboot

### ISSUE THREAD

**Issue by OriBenHur-Any** [OpenVPN/openvpn3-linux#15]
OS: ubuntu 20.04
openvpn3 version
```
OpenVPN 3/Linux v9_beta (openvpn3)
OpenVPN core 3.git:HEAD:811dac2e linux x86_64 64-bit
Copyright (C) 2012-2020 OpenVPN Inc. All rights reserved.
```

I'm using `openvpn3 config-import --config <path_to_ovpn_file>` to import my client config file to the store.
then I'm changing it's name to be somthing more easy to type 
`openvpn3 config-manage --path <config_path_from_configs-list> --rename <new_name>` 

All is good up until I reboot then I lose my configs and I need to do it all over again

**Comment by dsommers** [comment]
You need to import the configuration as a persistent configuration.  As indicated in the [openvpn3-config-import](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-config-import.1.rst)(1) man page:

       -p, --persistent
              By default, the configuration profile is kept  in  memory  only,
              and it is wiped when the configuration manager service restarts.
              When adding this option the profile becomes persistent and  will
              be  automatically  loaded  each  time  the configuration manager
              starts.

You can also set the new config name during import, using the `--name` argument to`openvpn3 config-import`; also described in the man page - and `openvpn3 config-import --help`.

    $ openvpn3 config-import --help
    openvpn3: config-import - Import configuration profiles
    
       -h | --help                 - This help screen
       -c | --config CFG-FILE      - Configuration file to import
       -n | --name NAME            - Provide a different name for the configuration (default: CFG-FILE)
       -p | --persistent           - Make the configuration profile persistent through service restarts

**Comment by OriBenHur-Any** [comment]
i have no idea how I've missed it 😅
thanks
