### ISSUE TITLE
Linux images on GCP fails to start netcfg due to inaccessible `openvpn` group

### ISSUE THREAD

**Issue by cmer81** [OpenVPN/openvpn3-linux#153]
Hello,

I can't use openvpn3 on linux environments at GCP anymore.
I systematically receive the error message:

```
net.openvpn.v3.log[642]: {tag:17274865932450918438} Session Manager !! CRITICAL !!: Failed communicating with VPN backend: Failed calling D-Bus method Connect: GDBus.Error:net.openvpn.v3.backend.error.standard: Failed executing D-Bus call 'Connect': Failed preparing proxy: Error calling StartServiceByName for net.openvpn.v3.netcfg: Launcher could not run (out of memory)
```
in my journalctl dbus i have this logs:

```
 Oct 03 14:02:47 xxx-openvpn dbus-daemon[561]: [system] Activated service 'net.openvpn.v3.netcfg' failed: Launcher could not run (out of memory)
Oct 03 14:02:47 xxx-openvpn org.freedesktop.DBus[7746]: {tag:15451295260794154855} Session Manager !! CRITICAL !!: Failed communicating with VPN backend: Failed calling D-Bus method Connect: GDBus.Error:net.openvpn.v3.backend.error.standard: Failed executing D-Bus call 'Connect': Failed preparing proxy: Error calling StartServiceByName for net.openvpn.v3.netcfg: Launcher could not run (out of memory)
```

I have reinstalled the server several times

- ubuntu 20.04
- ubuntu 22.04
- debian 11
- centos7

and I still have the same error.

`openvpn3-admin version --services`
```
OpenVPN 3 D-Bus services:

  - Client backend starter service
     openvpn3-service-backendstart: v18_beta

  - Configuration Service
     openvpn3-service-configmgr:    v18_beta

  - Log Service
     openvpn3-service-logger:       v18_beta

** ERROR ** Failed preparing proxy: Error calling StartServiceByName for net.openvpn.v3.netcfg: Launcher could not run (out of memory)
```
I need help :)

Regards

**Comment by dsommers** [comment]
Is this host running inside some kind of Dockerized environment?  That the `openvpn3-service-netcfg` service stops like that is quite odd.  But that is the process needing most privileges.

Can you try to start this service manually on the command line as root? Just start it like this:  `/usr/libexec/openvpn3-linux/openvpn3-service-netcfg --log-level 6 --log-file stdout:`

**Comment by cmer81** [comment]
Hi @dsommers,

I run openvpn3 directly on the GCE instance ubuntu 20.04.
for the command the server tells me that the file does not exist.

```
root@test-openvpn:/home/cmer# /usr/libexec/openvpn3-linux/openvpn3-service-netcfg --log-level 6 --log-file stdout:
bash: /usr/libexec/openvpn3-linux/openvpn3-service-netcfg: No such file or directory
```
The folder does not exist.
```
root@test-openvpn:/home/cmer# ls /usr/libexec/openvpn3-linux/
ls: cannot access '/usr/libexec/openvpn3-linux/': No such file or directory
```
About my version of openvpn3

```
oot@test-openvpn:/home/cmer# dpkg -l openvpn3
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-=================================
ii  openvpn3       18~beta1+focal amd64        OpenVPN 3 Linux client
```

and others information on this server 

![image](https://user-images.githubusercontent.com/5068536/193814417-0b1c22aa-6c06-417c-943e-d071247d4861.png)

**Comment by dsommers** [comment]
You need to look up the equivalent folder for the `libexec` directory on Ubuntu; I've forgotten where that is now.  Just list files in the openvpn3 package: `dpkg -L openvpn3 | grep netcfg`

**Comment by cmer81** [comment]
it returns the result

```
oot@test-openvpn:/home/cmer# /usr/lib/x86_64-linux-gnu/openvpn3-linux/openvpn3-service-netcfg --log-level 6 --log-file stdout:
Group 'openvpn' not found
root@test-openvpn:/home/cmer#
```

the group exists on this server

```
root@test-openvpn:/home/cmer# cat /etc/group |grep openvpn
openvpn:x:120:
```

**Comment by dsommers** [comment]
Ahh!  That rings a bell!  For some reasons there has been done some hacks on some cloud provider images to only consider user/group details from some central identity provider, and ignoring `/etc/group` and `/etc/passwd` ... you probably need to dig into the NSS stack and `/etc/nsswitch.conf` and related settings here.

**Comment by dsommers** [comment]
What does `getent group openvpn` return?

**Comment by cmer81** [comment]
He return this 

```
root@test-openvpn:/home/cmer# getent group openvpn
openvpn:x:120:
```

**Comment by cmer81** [comment]
OMG !! why didn't i think to make a strace first :exploding_head: 

the error seems clear with `strace`

```
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
```

after installing nscd everything works fine now: `sudo apt-get install -y nscd`

```
root@test-openvpn:/home/cmer# sudo openvpn3 sessions-list
-----------------------------------------------------------------------------
        Path: /net/openvpn/v3/sessions/ab86e479s64b4s44e0s8a62s9f8d551a24de
     Created: Tue Oct  4 13:34:48 2022                  PID: 779
       Owner: root                                   Device: tun0
 Config name: OpenVPNCloud
Session name: fr-cdg.gw.openvpn.com
      Status: Connection, Client connected
```

You can add `nscd` to the depency list 😁

**Comment by dsommers** [comment]
It might be we can extend that script somehow.  But blindly adding `nscd` can cause issues if the host is already configured to use `sssd` - which does somewhat similar tasks - and is a key component for [FreeIPA](https://www.freeipa.org/) enrolled hosts.

My `/etc/nsswitch.conf` (on RHEL-8) contains this comment:
```
# Notes:
#
# 'sssd' performs its own 'files'-based caching, so it should generally
# come before 'files'.
#
# WARNING: Running nscd with a secondary caching service like sssd may
#          lead to unexpected behaviour, especially with how long
#          entries are cached.
#
```

**Comment by dsommers** [comment]
This should be somewhat covered  by commit 76afb9486f1bc03b9fedd59f75d02e33d90a636d.
