### ISSUE TITLE
openvpn3-linux cannot reauthenticate via SAML  

### ISSUE THREAD

**Issue by premax** [OpenVPN/openvpn3-linux#154]
We are using OpenVPN Access Server v2.11 with SAML enabled (as default authentication system) to authenticate users to Azure AD.

First connection goes smooth - while executing openvpn3 command a new tab in browser is opened and user needs to authenticate to the provider. But after some time (2h?) user session is getting disconnected with the following error:

`Status: Connection, Client authentication failed: Authentication failed.`

![image](https://user-images.githubusercontent.com/1401870/196119053-ae2f1bbf-7ce8-4ceb-bcd7-ce4e2c512ab9.png)

Openvpn3-linux client probably does not try to call browser to refresh authentication (as Windows client does), because no browser activitity is visible. 

Client version: OpenVPN 3/Linux v18_beta, tested on Ubuntu 18.04 Desktop and Ubuntu 20.04 Desktop.

Any suggestions?

**Comment by dsommers** [comment]
This is a known issue and we're trying to resolve this issue for v19_beta.  As a workaround, you can try to to add `setenv opt USERNAME $your_saml_username` in the configuration profile.

If you have used the `openvpn3-as` utility to import the config profile, you can use this approach

      $ openvpn3 config-dump --config $CONFIG_NAME > as-profile.conf
      $ echo "setenv opt USERNAME $saml_username" >> as-profile.conf
      $ openvpn3 config-manage --config $CONFIG_NAME --rename $BACKUP_CONFIGNAME
      $ openvpn3 config-import --persistent --config as-profile.conf --name $CONFIG_NAME

Then you start the session as before: `openvpn3 session-start --config $CONFIG_NAME`

**Comment by dsommers** [comment]
This should be fixed for the time being with commit 6993bd91859bc4b108dbe4408f6fc25b568aadda.  This fix unfortunately requires the VPN configuration file to be imported again, so the configuration profile is correctly set up.

Another better fix will come in a later release.

**Comment by premax** [comment]
Thank you, `setenv opt USERNAME $your_saml_username` solves the issue for us too.

**Comment by dsommers** [comment]
This has been resolved in the [v19_beta](https://github.com/OpenVPN/openvpn3-linux/releases/tag/v19_beta) release.
