### ISSUE TITLE
Build doesn't work without selinux

### ISSUE THREAD

**Issue by MFAshby** [OpenVPN/openvpn3-linux#16]
Steps to reproduce:
- be on a linux distro with no selinux (I'm using manjaro ARM)
- run ./bootstrap.sh then ./configure ... as per building from source instructions
- configure exits with an error (details below) 
- include the flag --disable-selinux-build as per the instructions in `./configure --help`

Expected behaviour
- ./configure command completes successfully

Actual behaviour
- ./configure command still exits with the same error

Error message during configure, which I receive regardless of the --disable-selinux-build flag:
```
configure: Using ASIO source directory: ./vendor/asio
configure: Using OpenVPN 3 Core Library directory: ./openvpn3-core
checking OpenVPN 3 Core Library version... 3.git:HEAD:bf9f309f
./configure: line 7436: syntax error near unexpected token `${datarootdir}/selinux/devel,'
./configure: line 7436: `        AX_RECURSIVE_EVAL(${datarootdir}/selinux/devel, selinux_devel_path)'
```

I worked around this by simply editing  and manually deleting the section about selinux from the configure script. Ideally the script would correctly detect selinux availability and exclude generating the policy files if it's not present on the system.

**Comment by dsommers** [comment]
Can you please verify you have autoconf-archive package installed?  The AX_* macros in ./configure is from the autoconf-archive.  The upstream autoconf-archive project can be found here, for details: https://www.gnu.org/software/autoconf-archive/

**Comment by MFAshby** [comment]
Ah I didn't! 

This is already included in the docs for fedora, ubuntu etc, https://github.com/OpenVPN/openvpn3-linux#fedora, I just missed it. 

Thanks, and sorry for the bother.
