### ISSUE TITLE
Open vpn client work with LAN but Not Working with wifi

### ISSUE THREAD

**Issue by dipenpatel235** [OpenVPN/openvpn3-linux#163]
Hello,

I have set up OpenVPN a server in AWS cent os.  And my client runs on ubuntu 20.0
I am able to access the OpenVPN server and access servers via LAN. 
But when I connect with the wife I am able to connect VPN properly. But I am not able to access the x.xx.xxx.xxx server that I access by LAN.

Client interface when using via wifi: wlp0s20f3
client private IP and subnet: 192.168.1.165/24

OpenVPN server.conf

```
port 1194
proto tcp
dev tun
user nobody
group nobody
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
#push "redirect-gateway def1 bypass-dhcp"
push "route 10.8.0.0 255.255.255.0"
push "route 172.31.0.0 255.255.0.0"
push "dhcp-option DOMAIN gitlab.stockviz.com"
push "route x.xxx.xxx.xxx 255.255.255.255"
dh none
ecdh-curve prime256v1
tls-crypt tls-crypt.key
crl-verify crl.pem
ca ca.crt
cert server_X38yEQrYMyzhTWrZ.crt
key server_X38yEQrYMyzhTWrZ.key
auth SHA256
cipher AES-128-GCM
ncp-ciphers AES-128-GCM
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
client-config-dir /etc/openvpn/ccd
status /var/log/openvpn/status.log
verb 3
```

Client.ovpn

```
client
proto tcp-client
remote x.xx.xxx.xxx 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_X38yEQrYMyzhTWrZ name
auth SHA256
auth-nocache
cipher AES-128-GCM
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
<ca>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</ca>

<cert>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</cert>
<key>
-----END PRIVATE KEY-----
</key>
<tls-crypt>

<tls-crypt>
#
# 2048 bit OpenVPN static key
#

</tls-crypt>
```

**Comment by dsommers** [comment]
If you can connect fine via wired Ethernet but not via wifi, that indicates an issue with the wifi router setup.  OpenVPN (any version, any platform) does not really care much at all which kind of interface it connects via.  As long as the TCP/IP configuration is correct and the port the OpenVPN server is not blocked by a firewall etc, that's all OpenVPN need.

**Comment by dipenpatel235** [comment]
Hello @dsommers,

Can you please help me to fix my routing issue?

Thanks,
Dipen.

**Comment by dsommers** [comment]
@dipenpatel235 This is more a question for https://forums.openvpn.net/ or the [#openvpn IRC channel](https://community.openvpn.net/openvpn/wiki/GettingHelp#UserIRCchannel).

This place is for reporting bugs with OpenVPN 3 Linux.
