### ISSUE TITLE
Non-systemd build broken

### ISSUE THREAD

**Issue by RaphMad** [OpenVPN/openvpn3-linux#167]
Building from sourcein a non-systemd environment results in the following error:

```
In file included from src/ovpn3cli/commands/journal.cpp:19:
./src/log/journal-log-parse.hpp:18:10: fatal error: systemd/sd-journal.h: No such file or directory
   18 | #include <systemd/sd-journal.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I think all code related to journal logging should be optional via guards similar to https://github.com/OpenVPN/openvpn3-linux/pull/145/commits/cc06af0e38f5f93a51dfd23f3868f81ebe6efc29.

**Comment by dsommers** [comment]
Hey!  Thanks for reporting this ... again :slightly_smiling_face: 

Can you see if commit 012ae40e61c091a5a8615c solves it for you?

**Comment by RaphMad** [comment]
Fixed!

(I'm regularly building an alpine-based container from the latest sources, so I notice breaks that only occur without systemd and/or musl)

**Comment by dsommers** [comment]
Thanks a lot, @RaphMad!  Those efforts are highly appreciated!
