### ISSUE TITLE
openvpn3-service-logger does not start on non-systemd systems

### ISSUE THREAD

**Issue by mariolpantunes** [OpenVPN/openvpn3-linux#169]
Some context, I am using Slackware64-current and made a slackbuild for openvpn3-linux application.
I follow the instructions on the README.md on how to build the application.
However, whenever I try to run the following command
`openvpn3 config-import --config vpn.ovpn`

it fails with a D-Bus error.

This is the [script](https://github.com/mariolpantunes/slackware/blob/master/slackbuilds/openvpn3-linux/openvpn3-linux.SlackBuild) that I am using to compile the code.

Any hints on how to fix this?

**Comment by dsommers** [comment]
Can you try to run `openvpn3-admin version --services` as `root`?

Check the syslog files and see what errors appears there.  It would also be helpful to see the complete output of the compilation.

**Comment by mariolpantunes** [comment]
This is the result
```
openvpn3-admin version --services
OpenVPN 3 D-Bus services:

** ERROR ** Failed preparing proxy: Error calling StartServiceByName for net.openvpn.v3.backends: Launcher could not run (out of memory)
```

**Comment by dsommers** [comment]
What does your syslog say?

Btw ... Have you created the `openvpn` user and group?

**Comment by mariolpantunes** [comment]
The group and user were created as stated in the README.md
There is no messages in the syslog when I execute
`openvpn3-admin version --services`

**Comment by dsommers** [comment]
okay, this is getting hard to debug.  How is your slackware configured to do logging?  You should look for some 'dbus' errors in `/var/log` normally.  But seeing the output of the `./configure` and `make` steps would help seeing how the build-time configuration is setup too.

**Comment by dsommers** [comment]
Can you try to start `openvpn3-service-logger` manually?  What's the output it produces?

**Comment by mariolpantunes** [comment]
Found the dbus log, the error that appears is the following:
```
Feb 17 12:23:45 rincewind root: ACPI action up is not defined
Feb 17 12:23:45 rincewind dbus-daemon[1850]: [system] Activating service name='net.openvpn.v3.backends' requested by ':1.192' (uid=0 pid=15285 comm="openvpn3-admin version --services") (using servicehelper)
Feb 17 12:23:45 rincewind dbus-daemon[1850]: [system] Activating service name='net.openvpn.v3.log' requested by ':1.193' (uid=213 pid=15289 comm="/usr/libexec/openvpn3-linux/openvpn3-service-backe") (using servicehelper)
Feb 17 12:23:45 rincewind dbus-daemon[1850]: [system] Activated service 'net.openvpn.v3.log' failed: Launcher could not run (out of memory)
Feb 17 12:23:45 rincewind dbus-daemon[1850]: [system] Activated service 'net.openvpn.v3.backends' failed: Launcher could not run (out of memory)
```

**Comment by mariolpantunes** [comment]
The output of the `./configure` is the following:

```
** Updating version.m4 ...
Version: v19_beta

** Running autoreconf ...
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:27: installing './compile'
configure.ac:24: installing './install-sh'
configure.ac:24: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
src/python/Makefile.am:38: installing './py-compile'
autoreconf: Leaving directory '.'

checking for a BSD-compatible install... /usr/bin/ginstall -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking how to run the C preprocessor... gcc -E
checking for ranlib... ranlib
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking whether make sets $(MAKE)... (cached) yes
checking whether g++ supports C++11 features by default... yes
checking whether g++ supports C++14 features by default... yes
checking for a Python interpreter with version >= 3.5... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.9
checking for python3 platform... linux
checking for GNU default python3 prefix... ${prefix}
checking for GNU default python3 exec_prefix... ${exec_prefix}
checking for python3 script directory (pythondir)... ${PYTHON_PREFIX}/lib64/python3.9/site-packages
checking for python3 extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib64/python3.9/site-packages
checking for liblz4... yes
checking for jsoncpp... yes
checking for gio-2.0... yes
checking for gio-unix-2.0... yes
checking for uuid... yes
checking for libcap-ng... yes
checking for libsystemd > 218... no
checking for tinyxml2... yes
checking presence of XMLDocument::ErrorName... yes
checking presence of XMLDocument::ErrorStr... yes
checking for openssl >= 1.0.2... yes
configure: Using ASIO source directory: ./vendor/asio
configure: Using OpenVPN 3 Core Library directory: ./openvpn3-core
checking OpenVPN 3 Core Library version... 3.git:HEAD:04af83e0
configure: Found /etc/os-release ... parsing it
configure: Operating system: Slackware 15.0
configure: Default DNS resolver configuration: --resolv-conf /etc/resolv.conf
configure: Using ovpn-dco source directory: ./ovpn-dco
configure: Checking for SELinux policy development files
checking for /usr/share/selinux/devel/Makefile... no
checking for /usr/share/selinux/devel... no
checking for rst2man... rst2man
checking for git... git
checking if this is a git checkout ... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating distro/systemd/Makefile
config.status: creating doxygen/Makefile
config.status: creating doxygen/openvpn3-linux.doxy
config.status: creating docs/man/Makefile
config.status: creating src/policy/Makefile
config.status: creating src/python/Makefile
config.status: creating src/selinux/Makefile
config.status: creating src/service-autostart/Makefile
config.status: creating addons/aws/Makefile
config.status: creating config.h
config.status: executing depfiles commands
```

**Comment by dsommers** [comment]
Can you run in a separate terminal this command:

     /usr/libexec/openvpn3-linux/openvpn3-service-logger --service --timestamp --log-level 6 --state-dir /var/lib/openvpn3 --idle-exit 0

Then in yet another terminal, run this command: 

     /usr/libexec/openvpn3-linux/openvpn3-service-configmgr --log-level 6 --log-file stdout: --state-dir /var/lib/openvpn3 --idle-exit 0

It might be the path is slightly different.  The path used is `libexecdir` in `config.log`.

Also check that the ǹet.openvpn.v3.*.service` files in `/usr/share/dbus-1/system-services/`  has the proper path to the `openvpn3-service-*` binaries.  The D-Bus path above based on the `dbus_system_servicedir` path in `config.log`.

Often dbus-daemon errors like `Launcher could not run (out of memory)` is a bit misleading, as the "out of memory" seems to happen each time it has problems executing anything, for whatever reason - including privilege issues, missing directories or even missing user/group accounts.

**Comment by mariolpantunes** [comment]
Running the last two commands I get:

```
/usr/libexec/openvpn3-linux/openvpn3-service-logger --service --timestamp --log-level 6 --state-dir /var/lib/openvpn3 --idle-exit 0
[INFO] Dropping root group privileges to openvpn
[INFO] Dropping root user privileges to openvpn
2023-02-19 19:20:55  Logger INFO: OpenVPN3/Linux git:HEAD:33da965fa4151a05 (openvpn3-service-logger)
OpenVPN core 3.git:HEAD:04af83e0 linux x86_64 64-bit
Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
2023-02-19 19:20:55  Logger INFO: Log method: StreamWriter
2023-02-19 19:21:06  Logger VERB2: Attached: {tag:5752061261848927224}  [:1.183/net.openvpn.v3.configuration]
2023-02-19 19:21:06  {tag:5752061261848927224} Config Manager DEBUG: ConfigManagerObject registered on 'net.openvpn.v3.configuration':/net/openvpn/v3/configuration
```


```
/usr/libexec/openvpn3-linux/openvpn3-service-configmgr --log-level 6 --log-file stdout: --state-dir /var/lib/openvpn3 --idle-exit 0
[INFO] Dropping root group privileges to openvpn
[INFO] Dropping root user privileges to openvpn
OpenVPN3/Linux git:HEAD:33da965fa4151a05 (openvpn3-service-configmgr)
OpenVPN core 3.git:HEAD:04af83e0 linux x86_64 64-bit
Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
2023-02-19 19:21:06  Config Manager DEBUG: ConfigManagerObject registered on 'net.openvpn.v3.configuration':/net/openvpn/v3/configuration
```

**Comment by dsommers** [comment]
That looks good.  You can start some of these manually.  Then I have a feeling it's something off in the D-Bus auto-start service files.

Can you check that the paths in `/usr/share/dbus-1/system-services/net.openvpn.v3.*.service` files?  That they point at the same directory and the corresponding binary?

Have you rebooted after installing openvpn3-linux?  If not, you might need to reload the D-Bus daemon.  Since I don't expect you to use systemd, you can do this directly with `dbus-daemon`:

     # gdbus call --system --dest org.freedesktop.DBus --object-path /org/freedesktop/DBus --method org.freedesktop.DBus.ReloadConfig

**Comment by mariolpantunes** [comment]
Found the issue, in the file `net.openvpn.v3.log.service` the exec is
```
[D-BUS Service]
Name=net.openvpn.v3.log
User=openvpn
Exec=/usr/libexec/openvpn3-linux/openvpn3-service-logger --service --state-dir "/var/lib/openvpn3" --log-level 4 --journald
```

The option `--journald` is not recognized.
Since my system does not use systemd, is there any way to prevent this option from being added?

**Comment by dsommers** [comment]
Ahh!  This makes sense!  This is a bug actually; I'll try to see if I can manage to squeeze this one in into the next v20 release.

Okay, so the quick workaround to override this command line argument, as root run:

     # openvpn3-admin log-service --config-file-override /var/lib/openvpn3/log-service.json --config-unset journald
     # openvpn3-admin log-service --config-file-override /var/lib/openvpn3/log-service.json --config-set syslog true

The first one is more or less just a precaution.  The second one will enforce syslog to be used.

This will not change the autostart service file, but the `log-service.json` config file will override the command line arguments.

Speaking of the v20 release; there will come a new command - `openvpn3-admin init-config`, which will attempt to auto-config a few critical settings based on the system it runs on.  This is going through final testing now before I'll update the git tree.

**Comment by dsommers** [comment]
Feel free to test this patch, which should use `--syslog` if systemd devel headers is not found.
https://gist.githubusercontent.com/dsommers/5369745b12ff82004d6c5cc0816e84fb/raw/4e1c6b9a57d1f31d9b93de3486034adb85d8a20e/no-systemd-syslog-fix.patch

**Comment by mariolpantunes** [comment]
I tried to apply this patch to branch v19 and main, but it failed.
Each version of the code should be used?

**Comment by dsommers** [comment]
you might need to use `patch -p1` when applying that patch, from the the root of the source tree

**Comment by dsommers** [comment]
This should be resolved with the v20 release.
