### ISSUE TITLE
Running OpenVPN3 on WSL2 Linux, Ubuntu-20.04, premission denied error

### ISSUE THREAD

**Issue by AnthonyHayes72** [OpenVPN/openvpn3-linux#175]
I'm trying to run OpenVPN3 on WSL2 Ubuntu-20.04 distro.

When I try to use openvpn3 commands, I am seeing permission denied errors...
![image](https://user-images.githubusercontent.com/128694731/232456860-4d627459-01ab-4613-8722-c199e9bcf518.png)

This is the version of openvpn...
![image](https://user-images.githubusercontent.com/128694731/232456970-ec3163a4-a5d8-48ba-abc5-0d2c42558b7c.png)

I have looked at other similar reported issues but none of the suggested solutions are working for me.

Further info as requested for other instances of this problem...

openvpn user and group exists...

![image](https://user-images.githubusercontent.com/128694731/232457640-a4e4ef35-5d28-4e8d-a3f7-b5689ba9e8c3.png)

dbus setup...

![image](https://user-images.githubusercontent.com/128694731/232457890-e1ee152a-8f2c-49aa-b9ca-1cf47066b073.png)

dbus introspection, (fails)...

![image](https://user-images.githubusercontent.com/128694731/232458027-ca2b807f-685a-4950-b95d-b96e5ec4218d.png)

I'm new to Linux, not sure what the dbus introspection failure indicates - any help much appreciated.

**Comment by AnthonyHayes72** [comment]
Managed to fix this by reinstalling DBus in my WSL instance
`sudo apt purge dbus` followed by `sudo apt install dbus`

**Comment by tbarbette** [comment]
Hi ! I have a similar issue, with a fresh WSL2 / Ubuntu 22.04 install.

```
openvpn3 session-start -c /etc/openvpn/client/profile-16079.ovpn
** ERROR ** Failed preparing proxy: Error calling StartServiceByName for net.openvpn.v3.sessions: Failed to execute program net.openvpn.v3.sessions: Permission denied
```

Removing dbus has a lot of side effects, moreover I don't think this is an acceptable alternative...

**Comment by tbarbette** [comment]
That did not work. I finally uninstalled dbus and reinstalled it as Anthony suggested, but that removed a few dozen packages at the same time... It still did not work, but after activating systemd and a reboot, it works now.

Is dbus absolutely necessary? It would be great to add WSL in the compatibility, but I understand it's only growing in usage now.
