### ISSUE TITLE
Unable to Build from source with Python later than version Python3.6

### ISSUE THREAD

**Issue by BobShoneBizOpsInfra** [OpenVPN/openvpn3-linux#183]
I am trying to build the source on Amazon Linux 2. This ships with Python 3.7

But OpenVPN3-linux appears to need python3.6 to run.
I have built python3.6 from source and installed, but once built I am receiving an error when trying to start the autoload service. It errors in system.d and is unable to find module openvpn3

Any assistance on getting this running with Python 3.7 would be great.

**Comment by dsommers** [comment]
Amazon Linux 2 is not supported at the moment.  You might get around these issues by building it from source.  The `mock` utility may be helpful.  Download the source RPM (`yumdownloader --source`) and run `mock -r amazonlinux-2-x86_64 $SRC_RPM`.

Amazon Linux is an odd distribution being somewhere in between RHEL and Fedora, and there are relatively few requests for this distribution.  You might generally find RHEL/Rocky Linux/Alma Linux or Fedora more easy to use in the longer run.
