### ISSUE TITLE
openvpn3 session-start command fails with libva error on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by marcossv9** [OpenVPN/openvpn3-linux#191]
Hi all,

I've recently updated my computer from Ubuntu 20.04 LTS to 22.04.2 LTS, and it seems like there is an issue with `libva` when running `openvpn3 session-start --config my-profile.ovpn`. It's important to mention that OpenVPN Access Server is integrated with Okta web authentication, so every time I want to connect to the vpn, the terminal opens up the browser and send an assertion to Okta.

Here is the full output of it:

```
openvpn3 session-start --config my-profile.ovpn
Using pre-loaded configuration profile 'my-profile.ovpn'
Session path: /net/openvpn/v3/sessions/SESSION_PATH
Web based authentication required.
Session running, awaiting external authentication.
Further manage this session using 'openvpn3 session-manage' and 'openvpn3 session-auth'

Opening in existing browser session.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

After the last output, it hangs there...

I've installed the latest openvpn3 client release with `sudo apt install openvpn3`.

openvpn3 client version:
```
OpenVPN3/Linux v20 (openvpn3)
OpenVPN core v3.7.2 linux x86_64 64-bit
Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
```

I've also tried installing the latest version of Chrome for Ubuntu and nothing...

`Version 114.0.5735.106 (Official Build) (64-bit)`

From what I've read, it might be related to the GPU acceleration in Chrome? (I disabled it just in case, but same issue. My computer has an NVIDIA GTX 1050Ti, not sure if that helps, tough).

In the meantime, I will install latest nvidia drivers and see if that helps.

Anyone else having the same issue?
Thanks in advance.

**Comment by marcossv9** [comment]
Update: after installing NVIDIA proprietary drivers, the issue has gone, and I was able to connect to my vpn correctly.

**Comment by dsommers** [comment]
Yeah, this is probably something related to when the browser was kicked off.  OpenVPN 3 Linux does not depend on require any GPU support at all.  There should be no linking against `libva.so` at all in OpenVPN 3 Linux.
