### ISSUE TITLE
AWS addon fails when using IMDSv2

### ISSUE THREAD

**Issue by mattjbyrd** [OpenVPN/openvpn3-linux#192]
As part of AWS best practice we run EC2 instances with IMDSv2 enforced. The AWS addon fails when using IMDSv2 with an error:

`openvpn3-service-aws[1354]: /usr/lib/x86_64-linux-gnu/openvpn3-linux/openvpn3-service-aws: Error preparing route context: Error preparing route context: could not fetch AWS identity document: GET http://169.254.169.254/latest/dynamic/instance-identity/document : 401 Unauthorized`

Is it possible to add IMDSv2 support?

**Comment by lstipakov** [comment]
Sorry for delay and thanks for letting us know. Let me reproduce the problem first.

**Comment by lstipakov** [comment]
@mattjbyrd I have pushed fixes (there were two issues with AWS addon) to my [fork](https://github.com/lstipakov/openvpn3/tree/lev/fix_aws_addon). The problems were in openvpn3-core, not in openvpn3-linux. Would you be able to build the Linux client on your own (pointing openvpn3-core submodule to my fork) and verify that it works for you?

**Comment by mattjbyrd** [comment]
Apologies for the delay.  Yes, will get this tested :)

**Comment by mattjbyrd** [comment]
@lstipakov can confirm that it now works with IMDSv2 using your fork.

**Comment by dsommers** [comment]
This should be resolved with commit 90b07a2e816e644c36d1707a9bd4d74244cf210a, which will be included in v21.  This ticket will be closed when v21 is released.
