### ISSUE TITLE
OpenVPN Client for Ubuntu 18.04LTS with NetPlan Issues

### ISSUE THREAD

**Issue by extremeskillz** [OpenVPN/openvpn3-linux#2]
Hi, 
I hope this is the right place for this as I couldn't put this in the OpenVPN section for issues. OpenVPN doesn't get DNS resolution on a connection under Ubuntu 18.04LTS since ubuntu went to Netplan for the networking stack. This is becoming an issues for me since this was working under 14.04 and 16.04. Connecting to a pfsense box i was able to do DNS and see the entire network. Under Ubuntu 18.04 I get a connection but broken network connection and not able to hit different vlans under the same pfsense systems. The GUI portion of the client works fine as far as importing configs and what not but the underlying stack is broken. Please advise.

Thanks.

**Comment by schwabe** [comment]
You probably talking about the regular openvpn client (completely different codebase). And not this is not the right place to report those issues. For openvpn2 configuration of DNS is up the distribution/frontend/ui tool to set DNS.

A better place to report this is to whatever UI you are using. This client currently does not even have a UI.
