### ISSUE TITLE
"./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var" error

### ISSUE THREAD

**Issue by bonaluo** [OpenVPN/openvpn3-linux#20]
./configure: line 7441: syntax error near unexpected token `${datarootdir}/selinux/devel,'
./configure: line 7441: `        AX_RECURSIVE_EVAL(${datarootdir}/selinux/devel, selinux_devel_path)'

**Comment by bonaluo** [comment]
I am using manjaro (xfce)

**Comment by dsommers** [comment]
I suspect you're missing the autoconf-archive package, which provides the AX_* macros.
