### ISSUE TITLE
Add step in the installation documentation.

### ISSUE THREAD

**Issue by medzdev** [OpenVPN/openvpn3-linux#202]
When following the steps from the [Installation for Debian/Ubuntu](https://openvpn.net/cloud-docs/owner/connectors/connector-user-guides/openvpn-3-client-for-linux.html#UUID-2ef80d97-34a0-1507-e0cc-3026517c3e00_section-idm45842961864096338180977913) I wasn't able to conclude the procedure.
In fact, it's missing a step to update the package manager repository, after registering the openvpn package manually. This should be executed before 6th step (`sudo apt install openvpn3`).
The missing command is `sudo apt update`

**Comment by schwabe** [comment]
I ping the team that is responsible for the website about that.

**Comment by medzdev** [comment]
Solved issue! Thanks for the attention.
