### ISSUE TITLE
dev and dev-type ignored

### ISSUE THREAD

**Issue by maurin-at-homiwoo** [OpenVPN/openvpn3-linux#211]
Hi all, 

I'm having trouble trying to setup a custom name for the interface of my vpn connection. The dev option seems to be simply ignored. 

Here is the configuration I'm using on the client side : 
```
client
proto udp
dev myvpn
dev-type tun
remote XXX.XXX.XXX.XXX PPPP
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name vps-aa1b6d08_f58152a2-eb4f-479e-a564-64925dba157b name
cipher AES-256-CBC
auth SHA256
auth-nocache
push-peer-info
verb 3
```

The interface created is always named tun0 (or tun1 if I already have another connection active). 

Here are the output of some command about my setup : 

```         
$ openvpn3 config-manage --show --config my-config
                 
          Name: my-config
          Read only: No
          Persistent config: No
          Data Channel Offload: No

  Overrides:  No overrides set.
```

```
$openvpn3-admin version --services

OpenVPN 3 D-Bus services:

  - Client backend starter service
     openvpn3-service-backendstart: v20

  - Configuration Service
     openvpn3-service-configmgr:    v20

  - Log Service
     openvpn3-service-logger:       v20

  - Network Configuration Service
     openvpn3-service-netcfg:       v20

  - Session Manager Service
     openvpn3-service-sessionmgr:   v20
```

```
$ sudo openvpn3-admin init-config

- Detected settings will be saved to disk? No

* Checking for OpenVPN user and group accounts
    Found:  openvpn user - uid 131
    Found:  openvpn group - gid 142

* Checking OpenVPN 3 Linux state/configuration directory
    Using directory: /var/lib/openvpn3
    Directory found

* Logger Configuration
    Configuration file: /var/lib/openvpn3/log-service.json
    systemd-journald active state: active
    :: Result ::  Will use systemd journald for logging
    !! Configuration UNCHANGED

* Network Configuration
    Configuration file: /var/lib/openvpn3/netcfg.json
    Found systemd-resolved
    Found accessible /etc/resolv.conf
    :: Result :: Will use systemd-resolved
    !! Configuration UNCHANGED

* Ensuring SELinux file labels are correct
    - Could not retrieve SELinux status; skipping
```

```
$ openvpn3-admin netcfg-service --config-show
Loading configuration file: /var/lib/openvpn3/netcfg.json
Configuration file error in /var/lib/openvpn3/netcfg.json: Could not open file
```

Thanks in advance !

**Comment by dsommers** [comment]
This is a known "issue".  With the 'tun' mode, it's not possible to set your own device name.  This is a limitation in the [OpenVPN 3 Core](https://github.com/openVPN/openvpn3/) library, which implements the OpenVPN protocol.

The quick-fix is, if you have that possibility, to switch to using the `ovpn-dco` interface instead.  That will take the `dev` option into consideration.  To enable DCO ...

* Upgrade to OpenVPN 3 Linux v21 (which has support for the newer and supported `ovpn-dco-v2` kernel module).  For Debian/Ubuntu, you need to reconfigure the package repository; details here: https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux
* Ensure you have the `openvpn-dco-dkms` (Debian/Ubuntu) or `kmod-ovpn-dco` (RHEL-8 and newer, Fedora) package installed and available (check `modinfo ovpn-dco-v2`)
* Run: `openvpn3 config-manage --show --config my-config --dco true`

Please ensure you have a VPN server capable of doing `AES-GCM` ciphers (available from OpenVPN 2.5 and newer).
When starting the session now, the connection should be using the `AES-GCM` cipher and unless there are other options not DCO compliant, you should see your own device name being used.

If your OpenVPN server runs at least v2.6, that will also have DCO support (need the same kernel module on the server side) ... then you might get a bit better performance as well.
