### ISSUE TITLE
DOMAIN-SEARCH (dhcp option 119) not implemented?

### ISSUE THREAD

**Issue by Bun-Bun** [OpenVPN/openvpn3-linux#212]
I'm trying to push multiple domain suffixes but get the error DOMAIN-SEARCH is not recognized. Is this not implemented in openvpn3? Or is the argument named something else?

**Comment by Bun-Bun** [comment]
I think I answered my own question by reading the docs. 

I should be using the new --dns arguments --dns server and --dns search-domains

**Comment by dsommers** [comment]
Yes, please do use the `--dns` options instead. Using the `dhcp-options` for DNS setup has become a nightmare, as what works on one OS platform there fails on another one.

We spent some time a couple of years ago to go through the DNS setup and needed options and ended up with `--dns` and also documenting it far better, just to avoid the same undefined behaviour.  OpenVPN 3 Linux v21 should have the very latest fixes for the `--dns` option included as well.
