### ISSUE TITLE
Kali Linux support

### ISSUE THREAD

**Issue by dave8898** [OpenVPN/openvpn3-linux#215]
When I try to install open VPN using the following guide 
https://openvpn.net/cloud-docs/owner/connectors/connector-user-guides/openvpn-3-client-for-linux.html
I get the following error code after using the sudo apt update command
└─$ sudo apt update 
Hit:1 http://kali.download/kali kali-rolling InRelease
Err:2 https://packages.openvpn.net/openvpn3/debian kali-rolling InRelease
  403  Forbidden [IP: 104.18.109.96 443]
Reading package lists... Done
E: Failed to fetch https://packages.openvpn.net/openvpn3/debian/dists/kali-rolling/InRelease  403  Forbidden [IP: 104.18.109.96 443]
E: The repository 'https://packages.openvpn.net/openvpn3/debian kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
   
Thanks in advance

**Comment by dsommers** [comment]
Kali Linux is not a Linux distribution we currently support, and it is not a distribution we currently plan on supporting in the reasonable future.

The "403" errors is basically the file storage's response to say "the requested directory is not available".
