### ISSUE TITLE
Fedora 39 COPR builds for X86_64

### ISSUE THREAD

**Issue by p5** [OpenVPN/openvpn3-linux#217]
Please can you enable the Fedora 39 OpenVPN COPR builds for x86_64 architecture.
I can see the other architectures are enabled and being published, just not x86_64.

I understand we will likely not have anything usable until #171 is resolved, but it would be nice to install OpenVPN3 and have it automatically update once the new releases are out.

Example error log:

<details>

```
0.797 Enabled rpm-md repositories: copr:copr.fedorainfracloud.org:dsommers:openvpn3 code docker-ce-stable rpmfusion-free rpmfusion-nonfree rpmfusion-nonfree-updates rpmfusion-free-updates updates fedora fedora-cisco-openh264 updates-archive
1.146 Updating metadata for 'copr:copr.fedorainfracloud.org:dsommers:openvpn3'...done
1.148 error: Updating rpm-md repo 'copr:copr.fedorainfracloud.org:dsommers:openvpn3': cannot update repo 'copr:copr.fedorainfracloud.org:dsommers:openvpn3': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for https://download.copr.fedorainfracloud.org/results/dsommers/openvpn3/fedora-39-x86_64/repodata/repomd.xml (IP: 108.138.85.40)
```
(source: https://github.com/rsturla/eternal-images/actions/runs/6982335181/job/19001293281?pr=15#step:7:877)

</details>

Apologies if I am missing something.

![image](https://github.com/OpenVPN/openvpn3-linux/assets/46304672/25440647-f4e3-4456-9015-1bbc84aef69a)
(source: https://copr.fedorainfracloud.org/coprs/dsommers/openvpn3/)

**Comment by dsommers** [comment]
The missing detail here is that smoke testing of openvpn3-linux on Fedora 38+ turns out to be really unstable and unreliable.
Unfortunately, fixing this issue was far more intrusive and time consuming than anticipated as well.  And I want to avoid getting even more new issues in the bug tracker with "it doesn't work!" as the main topic.

That the other arches are built ... that's surprising, as I don't recall enabling them at all.  I'll try to clean up this in the nearer future.

Work is happening and I hope to have something ready for testing in the coming weeks.  I'll push those builds out into a separate "experimental" repo once I have something which can actually start and stop a VPN tunnel more reliable.

**Comment by dsommers** [comment]
Not sure how many of you are paying attention to #171. But there has been some progress and there are code ready to be tested.  Currently it requires doing some compilation/build efforts based on some instructions.

For Fedora 39, that means first build and install the v21 release from source code (follow the BUILD.md instructions).  Then do another build based on these instructions: https://github.com/OpenVPN/openvpn3-linux/issues/171#issuecomment-1858487477 ... with that build installed, then you should be able to help testing.

I will also put some efforts providing some installable packages ... but that will need to come in coming weeks.

**Comment by justin-octo** [comment]
Something is wrong with the build.  I'm seeing the x86_64 for Fedora 39 being pushed to the wrong folder (or the 40 is named incorrectly).  Notice below how this is the `fedora-40-x86_64` folder, but all the files show `fc39.x86_64.rpm`.  
https://download.copr.fedorainfracloud.org/results/dsommers/openvpn3/fedora-40-x86_64/05835909-openvpn3/
```
openvpn3-20-2.fc39.src.rpm | 2023-Apr-21 22:36:00 | 4.43M | RPM File
-- | -- | -- | --
openvpn3-20-2.fc39.x86_64.rpm | 2023-Apr-21 22:36:02 | 897.29K | RPM File
openvpn3-addon-aws-20-2.fc39.x86_64.rpm | 2023-Apr-21 22:36:17 | 305.39K | RPM File
openvpn3-addon-aws-debuginfo-20-2.fc39.x86_64.rpm | 2023-Apr-21 22:36:15 | 2.14M | RPM File
openvpn3-client-20-2.fc39.x86_64.rpm | 2023-Apr-21 22:36:13 | 784.00K | RPM File
openvpn3-client-debuginfo-20-2.fc39.x86_64.rpm | 2023-Apr-21 22:36:07 | 5.70M | RPM File
openvpn3-debuginfo-20-2.fc39.x86_64.rpm | 2023-Apr-21 22:36:19 | 8.59M | RPM File
openvpn3-debugsource-20-2.fc39.x86_64.rpm | 2023-Apr-21 22:36:04 | 746.95K | RPM File
openvpn3-devel-20-2.fc39.x86_64.rpm | 2023-Apr-21 22:36:10 | 20.63K | RPM File
openvpn3-selinux-20-2.fc39.noarch.rpm
```

Also, this page REALLY needs an update. https://openvpn.net/cloud-docs/owner/connectors/connector-user-guides/openvpn-3-client-for-linux.html

**Comment by justin-octo** [comment]
Further, all the "release" show `2.fc39`
```
        {
            "name": "openvpn3-client-debuginfo",
            "epoch": 0,
            "version": "20",
            "release": "2.fc39",
            "arch": "x86_64"
        },
```
https://download.copr.fedorainfracloud.org/results/dsommers/openvpn3/fedora-40-x86_64/05835909-openvpn3/results.json

**Comment by justin-octo** [comment]
I don't understand why work on Fedora 40 (future release) is being done when 39 (current release) is not working for x86_64.

**Comment by dsommers** [comment]
This is propbably Fedora Copr infrastructure enabling F40 automatically when it was branched out.  I'll delete it until a release is ready.

For the time being, use the builds made available in this Copr repo: https://copr.fedorainfracloud.org/coprs/dsommers/openvpn3-devsnapshots/

The development snapshots are coming from the work happening in #171.  These development snapshots will eventually end up as the v22_dev release once that is fully ready, and at that point it will be provided in the Copr repos for Fedora 38+.

**Comment by dsommers** [comment]
The `v22_dev` release is now out, which should resolve this ticket.

**Comment by justin-octo** [comment]
Awesome.  Thanks for working on this.  I'll have to test it out on my VM.

**Comment by justin-octo** [comment]
Does not seem to work for Fedora 38 fresh install.

```
# yum copr enable dsommers/openvpn3
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you really want to enable copr.fedorainfracloud.org/dsommers/openvpn3? [y/N]: y
Error: It wasn't possible to enable this project.
Repository 'fedora-38-x86_64' does not exist in project 'dsommers/openvpn3'.
Available repositories: 'fedora-39-aarch64', 'fedora-rawhide-ppc64le', 'fedora-rawhide-x86_64', 'fedora-40-s390x', 'fedora-39-s390x', 'fedora-40-aarch64', 'fedora-rawhide-s390x', 'fedora-39-x86_64', 'fedora-rawhide-aarch64', 'fedora-39-ppc64le', 'fedora-40-x86_64', 'fedora-40-ppc64le'

If you want to enable a non-default repository, use the following command:
  'dnf copr enable dsommers/openvpn3 <repository>'
But note that the installed repo file will likely need a manual modification.
```

Key part of that message:
`Repository 'fedora-38-x86_64' does not exist in project 'dsommers/openvpn3'.`

**Comment by dsommers** [comment]
@justin-octo Fedora 38 went [EOL last month](https://endoflife.date/fedora), so that is no longer supported.  You need to upgrade to at least Fedora 39.
