### ISSUE TITLE
openvpn3-autoload stills asks for auth credentials

### ISSUE THREAD

**Issue by rajeshisnepali** [OpenVPN/openvpn3-linux#22]
Here's my .autoload config   
```
{
   "autostart": false,
    "name": "openvpn-in",
    "remote": {
        "proto-override": "udp",
        "timeout": "300",
        "compression": "asym"
    },
    "tunnel": {
        "ipv6": "default",
        "persist": true,
        "dns-setup-disabled": false
    },
    "user-auth": {
        "autologin": true,
        "username": "user",
        "password": "secret"
    } 
}
```

Here's my  configs list
```
Configuration path
Imported                        Last used                 Used
Name                                                      Owner
------------------------------------------------------------------------------
/net/openvpn/v3/configuration/2984ca8fxda0ax416ax997exc50ee5cad031
Tue Sep 15 13:33:59 2020        Tue Sep 15 13:34:28 2020  1
openvpn-in                                                rajesh
------------------------------------------------------------------------------
```

As soon as I try to connect with my session path, it prompts for an auth.
```
➜  openvpn3 session-start -p /net/openvpn/v3/configuration/2984ca8fxda0ax416ax997exc50ee5cad031
Session path: /net/openvpn/v3/sessions/2c82f155s145ds4f0dsa4f0s5bd678025e87
Auth User name: 

```

> Am I missing anything?

**Comment by dsommers** [comment]
Please read this post carefully: https://openvpn.net/openvpn-3-linux-and-auth-user-pass/

The .autoload file is only processed by `openvpn3-autoload`.

**Comment by rajeshisnepali** [comment]
I still can't figure out what I am missing. I've followed both [https://openvpn.net/openvpn-3-linux-and-auth-user-pass/](https://openvpn.net/openvpn-3-linux-and-auth-user-pass/) & [https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-autoload.8.rst](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-autoload.8.rst)

**Comment by dsommers** [comment]
The blog post does not use `openvpn3 session-start` to start the VPN session. It uses `openvpn3-autoload`.

The `openvpn3 session-start` command does **not** parse the `.autoload` file, where the user credentials is given. Only `openvpn3-autoload` parses that file.
