### ISSUE TITLE
bootstrap.sh error

### ISSUE THREAD

**Issue by craftmaster1231** [OpenVPN/openvpn3-linux#222]
I've tried to build V20 on Fedora 39. 
https://github.com/OpenVPN/openvpn3-linux/releases/tag/v20

Here is what I got when run `./bootstrap.sh`:
`
** Initializing git submodules ...
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
`

It is fair to notice that cloned version of repo builds with no errors.

**Comment by dsommers** [comment]
Yeah, I don't expect that to work.  That way of publishing release sources are not working that well.
The proper autotools generated source tarball can be found here:
* https://swupdate.openvpn.net/community/releases/openvpn3-linux-20.tar.xz
* https://swupdate.openvpn.net/community/releases/openvpn3-linux-20.tar.xz.asc

Those are the files used in all distro packaging.

You might beware of issue #171, so this may or may not work.  And it is highly dependent on the OpenVPN configuration as well.  That said, I'm trying really hard to have something testable this or next week with just a couple of new binaries replacing the most troublesome ones from the v21 release. I'll try to get an update to the #171 ticket towards the end of this week.
