### ISSUE TITLE
session-manage --cleanup doesn't always clean up?

### ISSUE THREAD

**Issue by adolson** [OpenVPN/openvpn3-linux#230]
Hello,

I noticed in sessions-list that I had several entries of auth failed ("Connection, Client authentication failed: Authentication failed"), which I presumed were left behind when my employer's VPN times out the connection (every 12 hours, I believe). I ran openvpn3 session-manage --cleanup, which cleaned out the stale connections. Perfect!

A couple days later, I notice the same thing, but this time, --cleanup thinks all the sessions are valid?

Is there something I can add to my ovpn profile to fully disconnect? Or is there a way to force cleanup of these without having to manually specify the path to each one?

**Comment by dsommers** [comment]
The `session-mange --cleanup` will only clean up sessions it cannot reach (like if the VPN backend died/crashed unexpectedly).  If you can reach the session via `openvpn3 session-manage --disconnect --config CONFIG_NAME`, it is still available - and that is the way to properly shutdown the connection.

I'm deep into the GH issue 171, which does a complete rework of the D-Bus implementation.  The session manager will also be migrated.  I will have this issue in mind when I start looking at the session manager (client is backend is basically done, working on the netcfg service now).

If you can document how you can reproduce this issue consistently, I will try to test this issue more carefully.  Also good to know what kind of server you connect against.

**Comment by dsommers** [comment]
Just a quick comment .... the _openvpn3-indicator_ is probably the best alternative.  That uses the proper D-Bus interfaces.  The _openvpn3-applet_ is just a shell script doing lots of `openvpn3` calls - that is prune to fail easily.

I've also attached a little tool which we will introduce in a future release.  That does nothing fancy in regards to session management, but it gives you a desktop pop-up notification whenever the status of VPN sessions changes.
[session-watcher.tar.gz](https://github.com/OpenVPN/openvpn3-linux/files/14096488/session-watcher.tar.gz)

To use it, install it using `sudo make install`.  Then as the currently logged in user, you can activate this like this:

      $ systemctl --user enable --now openvpn3-desktop-session-watcher.service


If you see a VPN session requiring re-authentication, you may try to check out the `openvpn3 session-auth` command.

**Comment by adolson** [comment]
I guess I will close this, as it appears to be working as designed
