### ISSUE TITLE
Failed to start session with CloudConnexa on Fedora Linux

### ISSUE THREAD

**Issue by kmaasrud** [OpenVPN/openvpn3-linux#243]
I'm trying to connect to a OpenVPN server that is managed with CloudConnexa. I've downloaded a `.ovpn` configuration file from the dashboard and am trying to load it via the command line. I get the following error:

```
$ openvpn3 session-start --config <config-name>.ovpn
Using configuration profile from file: <config-name>.ovpn
Session path: /net/openvpn/v3/sessions/b34d7f46s6018s4158sbcefs9499df610102
session-start: ** ERROR ** Failed to start session
```

I've tried both using the `openvpn3` that is available in [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=openvpn3&from=0&size=50&sort=relevance&type=packages&query=openvpn3) (version 20) and a binary that is compiled from master:

```
$ openvpn3 version
OpenVPN3/Linux git:master:edf113b8138a2e53+* (openvpn3)
OpenVPN core  linux x86_64 64-bit
Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
```

I'm using Fedora Linux 40, but I've had the same issue on Fedora Linux 39 and 38. Other users (running Windows, MacOS and Ubuntu) are able to connect successfully to the server, so this seems to be a client issue.

**Comment by dsommers** [comment]
Heisann!

You might need to use the development snapshots for Fedora at the moment; a huge refactoring is on-going .... https://github.com/OpenVPN/openvpn3-linux/issues/171#issuecomment-1976183069

For further log details ...
```
$ sudo openvpn3-admin log-service --log-level 6
$ openvpn2 --config <config-name>.ovpn --verb 6
```

That will hopefully give a better idea what goes wrong.

**Comment by kmaasrud** [comment]
It seems like just installing that snapshot helped resolve the issue! The same command now loads the webauth form and it seems like I'm connected. Takk så meget :smile: 

However, I'm a bit unsure whether the connection is working properly, as I cannot reach any local machines over SSH. Is there some specific configuration that is needed to allow SSH connections through the VPN? Are there other ways for me to test whether the VPN works correctly? Sorry in advance for the questions being unrelated to the main issue :sweat_smile:

**Comment by kmaasrud** [comment]
That came from a firewall setting on our part, so I will close the issue. Thanks for the very swift reply! Have a great day :smile:
