### ISSUE TITLE
Support Synology DSM?

### ISSUE THREAD

**Issue by scruel** [OpenVPN/openvpn3-linux#247]
Is there any way we can use ovpen-client3 on Synology DSM? It has no built-in package manager, and `opkg`  (entware) also haven't yet included it, thanks!

**Comment by dsommers** [comment]
This is currently not something we support.  This has been requested a few times, so if there is a growing demand for it it might be picked up at some point.  But I can't promise that will happen currently.

If someone from the community puts in the needed effort for thre DSM packaging, we will certainly review that and help find a way how to make this happen quicker.

**Comment by scruel** [comment]
I just built [openvpn3](https://github.com/OpenVPN/openvpn3) binary on Ubuntu, and got it to run successfully on DSM (with same architect), not sure for this openvpn3-linux repo because I haven't yet tried, but I think it will be just the same.
As now my requirement satisfied with your another project, closing issue.
