### ISSUE TITLE
Error after ArchLinux upgrade

### ISSUE THREAD

**Issue by iris-garcia** [OpenVPN/openvpn3-linux#251]
```
** ERROR ** D-Bus service 'net.openvpn.v3.sessions' did not start
```
```
OpenVPN3/Linux git:makepkg:edf113b8138a2e53 (openvpn3)
OpenVPN core  linux x86_64 64-bit
Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
```

I'm using the AUR package (which used to work)

**Comment by joeqiwx** [comment]
The same things happen on my machine, here are some things I found from the log
`Thu Apr 18 10:32:17 2024  {tag:16077892865223408084} Client **!! FATAL !!**: Error calling NetCfgDevice::Establish(): Failed calling D-Bus method [net.openvpn.v3.netcfg] net.openvpn.v3.netcfg.Establish: GDBus.Error:net.openvpn.v3.netcfg.error.generic: Failed executing D-Bus call 'Establish': tun_open_error: error opening tun device /dev/net/tun: No such device
`

**Comment by dsommers** [comment]
Please have a look at #171.

There is a lot of work happening in the [dev/gdbuspp-migration branch](https://codeberg.org/OpenVPN/openvpn3-linux/src/branch/dev/gdbuspp-migration/) on codeberg.org.  A couple of days ago I pushed out yet another update both binary builds for Fedora (via a [Fedora Copr](https://copr.fedorainfracloud.org/coprs/dsommers/openvpn3-devsnapshots/) repo and a [Ubuntu PPA](https://launchpad.net/~djpig/+archive/ubuntu/openvpn) repo.

It would be great if some Arch maintainers would provide a devsnapshot package as well.

**Comment by dsommers** [comment]
Since the [AUR](https://aur.archlinux.org/packages/openvpn3) is now updated for the v22_dev release, I presume this issue is resolved there. If not, please re-open this issue on [Codeberg](https://codeberg.org/OpenVPN/openvpn3-linux/issues).
