### ISSUE TITLE
Support for ubuntu 24.04

### ISSUE THREAD

**Issue by ederfmatos-exacta** [OpenVPN/openvpn3-linux#253]
Is there any provision for support for version 24.04 of Ubuntu (noble)?

**Comment by pushkargogte** [comment]
you can install openvpn3 from this ppa: https://launchpad.net/~djpig/+archive/ubuntu/openvpn

**Comment by dsommers** [comment]
Sorry for the late reply.  TL;DR: Use the PPA repo mentioned above.

I'm working on a huge required refactoring for newer Linux distributions shipping with glib2 2.76 and newer.  This library version is basically incompatible with OpenVPN 3 Linux v21 and older.  The refactored work is provided via the PPA repo mentioned.

For more details and reporting feedback and related issues can be done in #171.   I want to keep this ticket open, as this question will most likely come more frequently.  This ticket should be closed when #171 is fully resolved and closed.

**Comment by apallares19-sys** [comment]
is it possible this is not working well? https://launchpad.net/~djpig/+archive/ubuntu/openvpn
I was able to install openvpn3 running ubuntu 24.04 but I couldn't connect to the VPN. I'm trying to connect to the OpenVPN cloudconexa. it's supposed to open the browser to ingress my credentials and finish the authentication. this last part never took place. can someone confirm if it's facing the same issue?
here are the logs:

openvpn3 log log-level 6 --config /home/alejandro/Downloads/ubnt_latest.ovpn
Waiting for session to start ... Done
Attaching to session /net/openvpn/v3/sessions/72fe4b4as9727s477dsb519s7402caf1aebb
2024-05-15 16:28:44 [STATUS] Connection, Configuration OK: config_path=/net/openvpn/v3/configuration/a6e253d1x7962x4938xa024xce29c0860e1b
2024-05-15 16:28:44 Client INFO: Starting connection
2024-05-15 16:28:44 [STATUS] Connection, Client connecting
2024-05-15 16:28:44 Client INFO: Connecting
2024-05-15 16:28:44 [STATUS] Connection, Client connecting
2024-05-15 16:28:44 [STATUS] Connection, Client authentication failed: Authentication failed
2024-05-15 16:28:44 Client INFO: Stopping connection
2024-05-15 16:28:44 [STATUS] Connection, Client disconnecting
2024-05-15 16:28:44 [STATUS] Connection, Client process exited
Session closed

**Comment by idrum4316** [comment]
@apallares19-sys I had the same problem with my company's CloudConnexa VPN. I couldn't find a fix, so I reverted to Ubuntu 22.04 for now. Sorry I don't have a solution, but I can at least confirm it's not just you.

**Comment by diman82** [comment]
I'm getting the following error:
`session-start: ** ERROR ** User authentication failed`
Usually, at authentication phase, a new browser window should open, and I can authenticate to my corporate account, but that simply doesn't happen for some odd reason.
I'm on the latest dev package:
```
The following NEW packages will be installed:
  openvpn3
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,028 kB of archives.
After this operation, 7,979 kB of additional disk space will be used.
Get:1 https://ppa.launchpadcontent.net/djpig/openvpn/ubuntu noble/main amd64 openvpn3 amd64 21+gdbuspp240516-3+noble [2,028 kB]
Fetched 2,028 kB in 3s (738 kB/s)     
Selecting previously unselected package openvpn3.
(Reading database ... 251485 files and directories currently installed.)
Preparing to unpack .../openvpn3_21+gdbuspp240516-3+noble_amd64.deb ...
Unpacking openvpn3 (21+gdbuspp240516-3+noble) ...
Setting up openvpn3 (21+gdbuspp240516-3+noble) ...
Processing triggers for dbus (1.14.10-4ubuntu4) ...
Processing triggers for man-db (2.12.0-4build2) ...
dimam@dimam-ThinkStation-P350:~/Downloads$ 
dimam@dimam-ThinkStation-P350:~/Downloads$ 
dimam@dimam-ThinkStation-P350:~/Downloads$ openvpn3 session-start --config desktop_pc_nesher_dimam@seekingalpha_com@seekingalpha.openvpn.com_[Tel_Aviv].ovpn
Using configuration profile from file: desktop_pc_nesher_dimam@seekingalpha_com@seekingalpha.openvpn.com_[Tel_Aviv].ovpn
Session path: /net/openvpn/v3/sessions/136a0d1dsd758s4786sbb71s8e959560dc36
session-start: ** ERROR ** User authentication failed

```

**Comment by dsommers** [comment]
@diman82 As I wrote earlier in an [earlier comment here](https://github.com/OpenVPN/openvpn3-linux/issues/253#issuecomment-2079357496): 

> I'm working on a huge required refactoring for newer Linux distributions shipping with glib2 2.76 and newer. This library version is basically incompatible with OpenVPN 3 Linux v21 and older. The refactored work is provided via the PPA repo mentioned.
>
> For more details and reporting feedback and related issues can be done in https://github.com/OpenVPN/openvpn3-linux/issues/171. I want to keep this ticket open, as this question will most likely come more frequently. This ticket should be closed when https://github.com/OpenVPN/openvpn3-linux/issues/171 is fully resolved and closed.

**Comment by dsommers** [comment]
@diman82 sorry!  I snapped to quickly ... you are running the GDBus++ migrated build

I'm just about to wrap up a builds for QA which will be the final `v22_dev` release .... One that's done, I'll see if I can provide some earlier snapshot builds for you to test.  There's been several enhancements since the last PPA builds.

**Comment by diman82** [comment]
@dsommers Please tag me when you have the early snapshots for testing.

**Comment by dsommers** [comment]
QA is going through the final tests.  I expect QA's report by end of this week - unless something really severe is found last minute. Then the release machinery will be kicked off which leads to a final tests of the release builds before it's made available for the public.

Since the `v22_dev` release is a massive refactoring of core components of the OpenVPN 3 Linux code, we do some extended testing to ensure we have caught as many possible issues as possible and don't on important aspects regress from prior releases.  So far it's looking quite promising, but it's needed to allow QA to complete.

The [PPA mentioned higher up](https://github.com/OpenVPN/openvpn3-linux/issues/253#issuecomment-2113344589) carries the last available development snapshot, but there has been applied bug fixes since that build.  We don't plan on any further snapshots until the release point.

**Comment by h-hollies** [comment]
do you have an estimated release date for the 24.04 compatible version? i have been eagerly waiting for this since i upgraded to noble numbat :)

**Comment by dsommers** [comment]
@h-hollies We don't announce an ETA for releases. But the PPA repo mentioned here a few times do have fully functional builds for 24.04. That repo is provided by a colleague, so it can be considered an official development snapshot repo.

**Comment by dsommers** [comment]
See [this comment](https://github.com/OpenVPN/openvpn3-linux/issues/171#issuecomment-2173291430) for details on the upcoming release.  The `v22_dev` release is on the way out now.

**Comment by dsommers** [comment]
OpenVPN 3 Linux v22_dev has been released.  Please see the installation instructions for Ubuntu.  The `v22_dev` release targets only Ubuntu 24.04 and Fedora 39 and newer.

**Comment by dddw** [comment]
it seems this fix also works for 24.10 
since it isn't releases specially for this release I recommend **for now** installing openvpn3 via this way and use 'noble' instead of 'oracular' in the official guide:
https://openvpn.net/cloud-docs/tutorials/configuration-tutorials/connectors/operating-systems/linux/tutorial--learn-to-install-and-control-the-openvpn-3-client.html

**Comment by GrzegorzDrozd** [comment]
@dddw Did you had to do anything special? I am using v23 on Ubuntu 24.10 and it does not work :/

```openvpn3 version
OpenVPN3/Linux v23 (openvpn3)
OpenVPN core v3.10.1 linux x86_64 64-bit
Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
```
and during session creation:

```openvpn3 session-start --config work
Using pre-loaded configuration profile 'work'
Session path: /net/openvpn/v3/sessions/08b8bc44sb863s4744s9662seb4d444f0bad
openvpn3/session-start: ** ERROR ** User authentication failed
```

in logs:
```openvpn3 log --config work
Waiting for session to start ... Done
Attaching to session /net/openvpn/v3/sessions/3c289ea1s0e92s4624s82f1s0d1743d99d02
2024-11-09 14:21:58  [STATUS] Connection, Configuration OK: config_path=/net/openvpn/v3/configuration/74e24a6fx7d66x4630xbbb1xaed25b4eacdf
2024-11-09 14:21:58  Client INFO: Starting connection
2024-11-09 14:21:58  [STATUS] Connection, Client connecting
2024-11-09 14:21:58  Client INFO: Connecting
2024-11-09 14:21:58  [STATUS] Connection, Client connecting
2024-11-09 14:21:58  [STATUS] Connection, Client authentication failed: Authentication failed
2024-11-09 14:21:59  Client INFO: Stopping connection
2024-11-09 14:21:59  [STATUS] Connection, Client disconnecting
2024-11-09 14:21:59  [STATUS] Connection, Client process exited
Session closed
```

**Comment by dsommers** [comment]
Increase the log levels and see what that gives you.

     $ openvpn3 config-manage --config work --log-level 6
     $ sudo openvpn3-admin log-service --log-level 6

Then try starting the session once more.

**Comment by srulikuk** [comment]
hi 
(long time @dsommers, how are you?)

I just installed my first ubuntu 22.04 and can't connect to my VPN, found this page and followed through to the instructions.

I am using my own vpn server not "CloudConnexa" as mention in the instructions for the import config.

I get this error when i try importing my ovpn file (import works fine on 22.04 and in default 24.04 openvpn deb)

```
openvpn3 config-import --config /path/to/my.ovpn --name my-vpn --persistent
openvpn3/config-import: ** ERROR ** ERR_PROFILE_GENERIC: [inline], [inline], [inline], [inline]
```

Thanks for your help.

**Comment by dsommers** [comment]
Hi, @srulikuk 

First, this question belongs home in the Discussion section, not in a closed GH issue ticket.

You have an odd configuration file ... the `[inline]` normally does not belong into a configuration profile.  Those lines can be removed, since you already have the `<ca>...</ca>` lines there.

Please do follow-ups in the discussion section.

**Comment by schwabe** [comment]
the [inline] is something that some old tutorials are suggesting and it only works because it gets overwritten later and the OpenVPN 2.x parser then ignores the lines with [inline] as it only evaluates the config after it has been fully parsed. The 3.x parser does not like this invalid first occurance.

**Comment by srulikuk** [comment]
> Please do follow-ups in the discussion section.

Hi @dsommers do you mind providing a link to the discussion section, took me many hours to find this issue page.
Thanks

**Comment by dsommers** [comment]
@srulikuk At the top of this page: 
![image](https://github.com/user-attachments/assets/3b5ccbf8-a0b5-4f95-97e8-8955027d5a26)

**Comment by AneesHl** [comment]
> OpenVPN 3 Linux v22_dev has been released. Please see the installation instructions for Ubuntu. The `v22_dev` release targets only Ubuntu 24.04 and Fedora 39 and newer.

The installation instructions for Ubuntu don't work. The Instruction in the following [reply](https://github.com/OpenVPN/openvpn3-linux/issues/253#issuecomment-2410994304)  do work at least on Ubuntu 24.04
