### ISSUE TITLE
openvpn3-service-client misinterprets `--keepalive` option

### ISSUE THREAD

**Issue by ruileao** [OpenVPN/openvpn3-linux#26]
Hi,

I've exported openvpn config file from my Asus router and imported to ubuntu 20.10:
openvpn3 config-import --config client.ovpn
openvpn3 session-start --config-path /net/openvpn/v3/configuration/21672a50xbf... etc
When I try to login: auth user and password, I always get: session-start: ** ERROR ** Failed to start session

Could anyone help, please?

Best,
Rui

**Comment by dsommers** [comment]
Can you please try `openvpn2 --config client.ovpn --verb 6` and provide the complete log?

Alternatively, in a different terminal, run this command before starting the session: `openvpn3 log --config client.ovpn --log-level 6` and then `openvpn3 session-start --config client.ovpn`.  Please provide the complete log file, to better understand what is happening and how far you get.

**Comment by ruileao** [comment]
> Can you please try `openvpn2 --config client.ovpn --verb 6` and provide the complete log?
I get this:** ERROR ** /usr/bin/openvpn2: error: unrecognized arguments: --;compress lzo

> Alternatively, in a different terminal, run this command before starting the session: `openvpn3 log --config client.ovpn --log-level 6` and then `openvpn3 session-start --config client.ovpn`. Please provide the complete log file, to better understand what is happening and how far you get.
With the command:
$openvpn3 log --config client.ovpn --log-level 6
I get:
Waiting for session to start ...
And nothing happens then...

**Comment by dsommers** [comment]
The `openvpn2` run highlights the error.  You seem to have `--;compress lzo` which seems incorrect. Try removing that line entirely.

**Comment by ruileao** [comment]
Thank you, line deleted.
Now I get this:
openvpn2 --config client.ovpn --verb 6
6
Press CTRL-C to stop the connection


** ERROR ** org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:net.openvpn.v3.sessions.error: Failed communicating with VPN backend: Failed calling D-Bus method Connect: GDBus.Error:net.openvpn.v3.backend.error.standard: Failed executing D-Bus call 'Connect': Configuration parsing failed: ERR_PROFILE_OPTION: option_error: option 'keepalive' must have at least 3 arguments

**Comment by ruileao** [comment]
client.ovpn:

remote "aaa".com
float
nobind
proto udp
dev tun
sndbuf 0
rcvbuf 0
keepalive 10 30

# for OpenVPN 2.4 or older
comp-lzo yes
# for OpenVPN 2.4 or newer

auth-user-pass
client
auth SHA1
cipher AES-128-CBC
...

**Comment by dsommers** [comment]
You need to provide the complete config without private keys, seems to more issues with your config. Like `remote "aaa".com`. Quotes like that is something I've never seen. And it seems to be even more issues.

**Comment by ruileao** [comment]
Sorry about my odd notation "aaa".com.
Here it is:

remote xyz.asuscomm.com 1025
float
nobind
proto udp
dev tun
sndbuf 0
rcvbuf 0
keepalive 10 30

# for OpenVPN 2.4 or older
comp-lzo yes
# for OpenVPN 2.4 or newer

auth-user-pass
client
auth SHA1
cipher AES-128-CBC
remote-cert-tls server
<ca>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

</ca>

<cert>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

</cert>

<key>
-----BEGIN PRIVATE KEY-----
----END PRIVATE KEY-----

</key>

**Comment by dsommers** [comment]
Alright, so there is an odd bug related to parsing the `keepalive` option. I'm still debugging it, but it seems it is being split up somewhere in into two lines (`keepalive 10` and then `keepalive 30`).  This is completely unexpected and incorrect. This requires quite some debugging.

That said, if the server side uses `keepalive`, you don't need it in the client config (`ping` and `ping-restart` options will then be pushed from the server to the client.  Otherwise you can replace `keepalive 10 30` with `ping 10` and `ping-restart 30`, as the `keepalive` is just a kind of macro option (search for `--keepalive` [here](https://github.com/OpenVPN/openvpn/blob/master/doc/man-sections/link-options.rst) for details).

This bug will remain open until fixed.

**Comment by ruileao** [comment]
Good morning,
It worked, I changed keepalive instruction to pings has you said and... connected!
The problem I got this time was with protobuf17.
But after 1 hour I managed to solve it.
I will open another different comment for that.
Best,
Rui

**Comment by dsommers** [comment]
This should be resolved with commit 8147be71e42ab92261046ca49f0b0cd49385e55d.  This will be part of the next v12_beta release.

**Comment by ruileao** [comment]
Thank you!
