### ISSUE TITLE
Unknown options: "python.bytecompile"

### ISSUE THREAD

**Issue by matianhe3** [OpenVPN/openvpn3-linux#263]
Arch Linux install `yay -S openvpn3-git`

```
meson.build:8:0: ERROR: Unknown options: "python.bytecompile"

A full log can be found at /home/m/.cache/yay/gdbuspp-git/src/gdbuspp-git/build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: gdbuspp-git-exit status 4
==> Making package: openvpn3-git 21.r287.g8a13d1b-1 (Fri 07 Jun 2024 01:47:05 PM CST)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> gdbuspp-git
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
 -> error making: openvpn3-git-exit status 8
checking dependencies...

Packages (1) python-docutils-1:0.21.2-1
```

**Comment by dsommers** [comment]
It would be great if you could share the meson log, as indicated in the log above ...  `/home/m/.cache/yay/gdbuspp-git/src/gdbuspp-git/build/meson-logs/meson-log.txt`

**Comment by rzvncj** [comment]
What meson version are you using (you can find out with `meson --version`)?

**Comment by matianhe3** [comment]
> meson --version

meson --version
1.0.1

**Comment by matianhe3** [comment]
cat /home/m/.cache/yay/gdbuspp-git/src/gdbuspp-git/build/meson-logs/meson-log.txt
Build started at 2024-06-07T13:47:04.080793
Main binary: /opt/python3/bin/python3.11
Build Options: -Db_pie=true -Dpython.bytecompile=1 -Dprefix=/usr -Dlibexecdir=lib -Dsbindir=bin -Dauto_features=enabled -Dbuildtype=plain -Dwrap_mode=nodownload
Python system: Linux
The Meson build system
Version: 1.0.1
Source dir: /home/m/.cache/yay/gdbuspp-git/src/gdbuspp-git
Build dir: /home/m/.cache/yay/gdbuspp-git/src/gdbuspp-git/build
Build type: native build
Running command: /home/m/.cache/yay/gdbuspp-git/src/gdbuspp-git/scripts/get-git-ref
--- stdout ---
master_7d80f553d64ec647

--- stderr ---



meson.build:8:0: ERROR: Unknown options: "python.bytecompile"

**Comment by dsommers** [comment]
So the culprit here is probably the `-Dpython.bytecompile=1` argument ... which seems to be something the Arch Linux packaging infrastructure adds.  The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gdbuspp-git) does not explicitly set this flag.  That leads me to think you might be missing some base packages in your distribution.  I'm not an Arch Linux user, so I'm not sure where to go next.  But perhaps @rzvncj has some clues.

**Comment by rzvncj** [comment]
Hey, sorry for the late reply, I've been traveling. I won't return to my Arch Linux box for a few days yet, but I did look at this issue before leaving and I remember my meson version is 1.4.1. 1.0.1 is a very old version probably installed by some non-standard means (`pip`?).

The solution is to simply install [the official Arch Linux meson package](https://archlinux.org/packages/extra/any/meson/).
