### ISSUE TITLE
v12 is not asking for 2FA prompt

### ISSUE THREAD

**Issue by felixn-unity** [OpenVPN/openvpn3-linux#29]
Hi

openvpn3 v12 is not presenting 2FA prompt, we are using a Duo Security 2FA script on the server and works on latest OSX, Windows clients and on v11 for linux.

Thanks

**Comment by dsommers** [comment]
Hi,

Yes, we noticed this regression today as well.  I'm working on a fix.  Expect v13_beta to be released in not too long.

**Comment by Toukenize** [comment]
Hi @dsommers , is there any update on the fix?

Thanks.

**Comment by dsommers** [comment]
v13_beta is in QA now.

**Comment by dsommers** [comment]
The v13_beta release was published yesterday.  If this issue re-appears, please add a comment here.
