### ISSUE TITLE
Cannot build on openSUSE

### ISSUE THREAD

**Issue by rtyler** [OpenVPN/openvpn3-linux#33]
I'm trying to package openvpn3 for openSUSE and running into the following failures with `./configure`

```
checking for OPENSSL... yes
configure: Using ASIO source directory: ./vendor/asio
configure: Using OpenVPN 3 Core Library directory: ./openvpn3-core
checking OpenVPN 3 Core Library version... 3.git:HEAD:ce0c9963
configure: Using ovpn-dco source directory: ./ovpn-dco
./configure: line 7802: syntax error near unexpected token `${datarootdir}/selinux/devel,'
./configure: line 7802: `        AX_RECURSIVE_EVAL(${datarootdir}/selinux/devel, selinux_devel_path)'
```

I'm not sure where to start figuring this out :-/

**Comment by dsommers** [comment]
You are most likely missing the autoconf-archive package, which ships all the AX_* autoconf macros.

**Comment by rtyler** [comment]
@dsommers Thanks a lot for the pointer, that does look to have moved me further along!  Curious that those macros live off in another package.

**Comment by ayZagen** [comment]
@rtyler How did you succeed? I have installed all dependencies, but it still gives that error.

**Comment by rtyler** [comment]
@ayZagen hah, I didn't actually succeed, I gave up :laughing: 

Because of this I use openvpn as little as possible and via a fedora VM when absolutely necessary
