### ISSUE TITLE
openvpn3-autoload / ConfigParser.py do not allow the usage of possible argument

### ISSUE THREAD

**Issue by rloutrel** [OpenVPN/openvpn3-linux#36]
Given: The template configuration file from ubuntu 20.04 
```
$ openvpn3 version
OpenVPN 3/Linux v13_beta (openvpn3)
OpenVPN core 3.git:HEAD:ce0c9963 linux x86_64 64-bit
Copyright (C) 2012-2020 OpenVPN Inc. All rights reserved.

$ less  /usr/share/doc/openvpn/examples/sample-config-files/client.conf
```

When: Using the 'mute' parameter with openvpn3-autoload 
mute 20

Then:
* expected: the parameter is accepted
* found: (I am still verifying for route-method and route-delay) 
```
Traceback (most recent call last):
  File "/usr/sbin/openvpn3-autoload", line 83, in find_autoload_configs
    opts = openvpn3.ConfigParser(['openvpn3-autoload',
  File "/usr/lib/python3/dist-packages/openvpn3/ConfigParser.py", line 89, in __init__
    self.__opts = vars(self.__parser.parse_args(self.__args))
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1886, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3/dist-packages/openvpn3/ConfigParser.py", line 863, in __call__
    args = vars(parser.parse_args(shlex.split('\n'.join(cfg),
  File "/usr/lib/python3.8/argparse.py", line 1783, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python3/dist-packages/openvpn3/ConfigParser.py", line 64, in error
    raise Exception("%s: error: %s"  % (self.prog, message))
Exception: openvpn3-autoload: error: unrecognized arguments: --route-method exe --mute 20 --route-delay 2
```

**Comment by dsommers** [comment]
Hi,

Thanks for the report.  These all seems to be options we need to add to the ignore list; neither of them exists for the OpenVPN 3 Core library and they make little sense in the OpenVPN 3 context.  For the time being, `--route-method`, `--mute`  and `--route-delay` can all be removed from your current config.

**Comment by rloutrel** [comment]
I am working on a PR. For the mute parameter it seems quite easy. for the 2 others, I am not sure about the acceptable formats.

Is there anywhere an official documentation?

**Comment by dsommers** [comment]
Awesome!  Please send these patches to the openvpn-devel@lists.sourceforge.net mailing list; see the wiki page for some more details: https://community.openvpn.net/openvpn/wiki/DeveloperDocumentation

All of these three options can go into the "ignored section" of [ConfigParser.py](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/python/openvpn3/ConfigParser.py#L664).  For the option syntax, see the OpenVPN 2.x man pages ([--route-method](https://github.com/OpenVPN/openvpn/blob/master/doc/man-sections/windows-options.rst), [--route-delay](https://github.com/OpenVPN/openvpn/blob/master/doc/man-sections/vpn-network-options.rst))

**Comment by rloutrel** [comment]
Patch submitted. I had to create a new mail address to avoid mine to be public.

Quite a bit complicated process, but I hope I helped.

**Comment by dsommers** [comment]
Great! Thanks a lot!  I will review it properly next week and merge it.  At first glance it looks good.

The process may seem complicated, but it ensures that the review is preserved even if GitHub disappears in the future, due to the distributed nature of e-mail and mailing lists.  It will always be possible to nest up why a change appeared later, something which is important for security products like VPN solutions.

**Comment by dsommers** [comment]
Thank you very much.  This has been reviewed and applied to git master, commit b1a270062e3d35dcf73f57340bd85fcb3d84b4cc
