### ISSUE TITLE
Routing using host names does not work

### ISSUE THREAD

**Issue by nordfalk** [OpenVPN/openvpn3-linux#37]
Is seems that routes using hostnames doesent work in  .ovpn files, 

Example:  `route xyz.blabla.dk 255.255.255.255` is ignored.

Whereas: `route 41.114.122.15 255.255.255.255` works.

$ openvpn3 version
OpenVPN 3/Linux v13_beta (openvpn3)
OpenVPN core 3.git:HEAD:ce0c9963 linux x86_64 64-bit
Copyright (C) 2012-2020 OpenVPN Inc. All rights reserved.

**Comment by nordfalk** [comment]
I have the  allow-pull-fqdn keyword in my .opvn file.
Is it ignored like it seems to be in openvpn? 

https://community.openvpn.net/openvpn/ticket/1227


It would be nice with some kind of warning on which keywords are ignored when you do an `openvpn3 config-import`

**Comment by dsommers** [comment]
Good point!  `openvpn3 config-import` doesn't really do magic, it just ensures it has all the data needed for the `openvpn3-service-client` process to run unprivileged and without direct access to the keying material needed to establish the connection.  

The `openvpn3-service-client` should report "UNUSED OPTIONS" in the the log (you can run `openvpn3 log --log-level 6 --config $CONFIG_NAME` in a different terminal before starting the session).  But it would be even nicer if `openvpn3 config-import` could do it.

It sounds easy enough, but the option parsing isn't as straight forward in the [OpenVPN 3 Core](https://github.com/OpenVPN/openvpn3/) library, unfortunately.  But I'll give it a shot and target this for a future release.

**Comment by nordfalk** [comment]
Thanks for the reply and the suggenstions!!

Ive managed to work around this by replacing DNS names with IPadresses:

grep -v "route [a-z]" config-with-dnsnames.ovpn > config-with-ipadresses.ovpn; 
for i in `grep "route [a-z]" config-with-dnsnames.ovpn | cut -d ' ' -f2`; do echo "route `dig +short $i|tail -1` 255.255.255.255 # $i"; done >> config-with-ipadresses.ovpn

Now it works for me.

I suggest you keep this issue open, so that others can see the workaround and how to do the logging you suggest: We 'mortals' that dont know much about VPN or openvpn3 but just want to get it working can then see what to do :-)

**Comment by dsommers** [comment]
I have decided to close this issue, as this is related to the [OpenVPN 3 Core](https://github.com/OpenVPN/openvpn3/) library and not this Linux client building on that library.  This is not something we will change or fix in the openvpn3-linux project alone.

**Comment by oawang** [comment]
mark openvpn route domain
