### ISSUE TITLE
Repository - considder adding the [arch=] parameter to (deb) sources lists

### ISSUE THREAD

**Issue by Lukas-UAUX** [OpenVPN/openvpn3-linux#38]
Hi,

you may want to add the [arch=] parameter to your downloadable (deb) sources lists, defining the available architectures ege. `deb [arch=amd64] https://swupdate.openvpn.net/community/openvpn3/repos buster main`.

On Systems that have enabled i386 `apt/apt-get update` throws a warning otherwise that the repository "..doesn't support architecture 'i386'"

**Comment by dsommers** [comment]
Thanks!  I'll do that.

**Comment by chris-bishop** [comment]
Hello!

I was just about to raise a similar concern whilst trying to install Debian 10 Buster pre-built binaries from repository...

I have recently built my first Raspberry Pi 4B+ SBC (for my personal development and engineering projects) and while working on getting my "golden image" created which contains every development framework, libs, dependencies, etc installed inside a fresh Raspberry Pi OS ("Raspbian") flash - I ran in to similar unsupported arch issue as well...

Here is some info on my RPi 4B+

`cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ ls -ltr /proc/cpuinfo 
-r--r--r-- 1 root root 0 Mar 14 04:44 /proc/cpuinfo
cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 144.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 144.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 144.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 144.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: d03114
Serial		: 1000000019dc0f0c
Model		: Raspberry Pi 4 Model B Rev 1.4
cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       117G   16G   97G  14% /
devtmpfs        3.8G     0  3.8G   0% /dev
tmpfs           3.9G   67M  3.8G   2% /dev/shm
tmpfs           3.9G  8.6M  3.9G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   48M  205M  19% /boot
tmpfs           788M   16K  788M   1% /run/user/1001
cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ free -m
              total        used        free      shared  buff/cache   available
Mem:           7875         605        6307         252         962        6783
Swap:            99           0          99
cbishop@raspberrypi:~ $ 
cbishop@raspberrypi:~ $ 
`
and here is the "unsupported arch" error I encounter during install:

`cbishop@raspberrypi:~/Documents/_ASUS_RT-AC66U/_20210314_OpenVPN_PrivTunnel_AshburnVA/openvpn3 $ sudo apt update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 https://download.mono-project.com/repo/debian vs-raspbianstretch InRelease
Hit:3 https://deb.nodesource.com/node_14.x buster InRelease                    
Get:4 https://swupdate.openvpn.net/community/openvpn3/repos buster InRelease [4,750 B]
Hit:5 http://raspbian.raspberrypi.org/raspbian buster InRelease                
Fetched 4,750 B in 2s (2,486 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://swupdate.openvpn.net/community/openvpn3/repos buster InRelease' doesn't support architecture 'armhf'
cbishop@raspberrypi:~/Documents/_ASUS_RT-AC66U/_20210314_OpenVPN_PrivTunnel_AshburnVA/openvpn3 $`

and here are the available options I have for install from managed packages:

`cbishop@raspberrypi:~/Documents/_ASUS_RT-AC66U/_20210314_OpenVPN_PrivTunnel_AshburnVA/openvpn3 $ sudo apt list openvpn
Listing... Done
openvpn/stable 2.4.7-1 armhf
cbishop@raspberrypi:~/Documents/_ASUS_RT-AC66U/_20210314_OpenVPN_PrivTunnel_AshburnVA/openvpn3 $ 

cbishop@raspberrypi:~/Documents/_ASUS_RT-AC66U/_20210314_OpenVPN_PrivTunnel_AshburnVA/openvpn3 $ sudo apt search openvpn
Sorting... Done
Full Text Search... Done
anytun/stable 0.3.7-1.1 armhf
  secure anycast tunneling protocol

collectd-core/stable 5.8.1-1.3 armhf
  statistics collection and monitoring daemon (core system)

easy-rsa/stable 3.0.6-1 all
  Simple shell based CA utility

eurephia/stable 1.1.0-6 armhf
  flexible OpenVPN authentication module

fastd/stable 18-3+deb10u1 armhf
  Fast and Secure Tunneling Daemon

gadmin-openvpn-client/stable 0.1.9-1 armhf
  GTK+ configuration tool for openvpn (client)

gadmin-openvpn-server/stable 0.1.5-3.1+b1 armhf
  GTK+ configuration tool for openvpn (server)

gadmin-openvpn-server-dbg/stable 0.1.5-3.1+b1 armhf
  GTK+ configuration tool for openvpn (debug for server)

gadmintools/stable 11 all
  GTK+ server administration tools (meta-package)

golang-github-apparentlymart-go-openvpn-mgmt-dev/stable 0.0~git20161009.9a305ae-1 all
  Go client library for OpenVPN's management protocol

kvpnc/stable 0.9.6a-4.1 armhf
  frontend to VPN clients

network-manager-openvpn/stable 1.8.10-1 armhf
  network management framework (OpenVPN plugin core)

network-manager-openvpn-gnome/stable 1.8.10-1 armhf
  network management framework (OpenVPN plugin GNOME GUI)

openvpn/stable 2.4.7-1 armhf
  virtual private network daemon

openvpn-auth-ldap/stable 2.0.3-6.1+b2 armhf
  OpenVPN LDAP authentication module

openvpn-auth-radius/stable 2.1-7 armhf
  OpenVPN RADIUS authentication module

openvpn-blacklist/stable 0.5+nmu1 all
  list of blacklisted OpenVPN RSA shared keys

openvpn-systemd-resolved/stable 1.2.7-1 armhf
  integrates OpenVPN with systemd-resolved

sslh/stable 1.18-1 armhf
  Applicative protocol multiplexer

wireguard/testing 1.0.20200827-1~bpo10+1 all
  fast, modern, secure kernel VPN tunnel (metapackage)

wireguard-dkms/testing 1.0.20210124-1~bpo10+1 all
  fast, modern, secure kernel VPN tunnel (DKMS version)

wireguard-tools/testing 1.0.20200827-1~bpo10+1 armhf
  fast, modern, secure kernel VPN tunnel (userland utilities)

yasat/stable 848-1 all
  simple stupid audit tool

cbishop@raspberrypi:~/Documents/_ASUS_RT-AC66U/_20210314_OpenVPN_PrivTunnel_AshburnVA/openvpn3 $`

Suggestions? Should I just settle for openvpn2 at this stage in this projects development, or might it be worth me making an attempt at cloning this repo and building from source against my own arch? (would clearly be willing to share my experiences there too! :)

Thank you for all the hard work!

**Comment by chris-bishop** [comment]
Sigh...please forgive my bad wiki formatting form...

switching back and forth all week between Git, Jira, Confluence, AWS, etc etc etc - most of which use different markdowns, I have "Fruedian slips" occaisonally! :)

**Comment by dsommers** [comment]
Currently we only have builds for x86_64/amd64 distros.

Both ARM and 32-bit distros are on our todo list, but if someone are willing to invest time providing patches and build instructions, we happily accept contributions. This will also help these issues be resolved quicker.

**Comment by chris-bishop** [comment]
Thanks for the reply @dsommers !

I'll definitely give building from source under my local arch as soon as I get some free cycles and let you know how I make out...

With the rapid increase in SBC popularity, etc - ARM arch package could be useful by other folks than myself...

**Comment by dsommers** [comment]
For the next v14_beta release we have been able to build proper ARM packages for Ubuntu and Debian. We will at least release them as a tech-preview.

**Comment by dsommers** [comment]
The armv7l/32-bit platform will be tracked in issue #49.  For arm64 on Debian and Ubuntu, that is part as a tech-preview for the v14_release going out today.
