### ISSUE TITLE
Can't install openvpn3 on ubuntu - wrong URLs

### ISSUE THREAD

**Issue by marcinkubica** [OpenVPN/openvpn3-linux#43]
Hi

```
wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$DISTRO.list``

--2021-04-28 10:12:56--  https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-.list
Resolving swupdate.openvpn.net (swupdate.openvpn.net)... 104.18.110.96, 104.18.109.96
Connecting to swupdate.openvpn.net (swupdate.openvpn.net)|104.18.110.96|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-28 10:12:56 ERROR 404: Not Found.
```
regards

**Comment by dsommers** [comment]
I presume you used instructions from here: https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux

The line above the wget line you used says:

        Replace $DISTRO with the release name depending on your Debian/Ubuntu distribution.

**Comment by marcinkubica** [comment]
@dsommers that's not how you do it in 2021 :) There's no such thing as "distro", there are distribution specifics.

What information are you actually after? 

```lsb_release(1)                                                                                       General Commands Manual                                                                                      lsb_release(1)

NAME
       lsb_release - print distribution-specific information

SYNOPSIS
       lsb_release [options]

DESCRIPTION
       The lsb_release command provides certain LSB (Linux Standard Base) and distribution-specific information.

       If no options are given, the -v option is assumed.

OPTIONS
       The program follows the usual GNU command line syntax, with long options starting with two dashes (`--').  A summary of options are included below.

       -v, --version
              Show the version of the LSB against which your current installation is compliant.  The version is expressed as a colon separated list of LSB module descriptions.

       -i, --id
              Display the distributor's ID.

       -d, --description
              Display a description of the currently installed distribution.

       -r, --release
              Display the release number of the currently installed distribution.

       -c, --codename
              Display the code name of the currently installed distribution.

       -a, --all
              Display all of the above information.

```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy

```

**Comment by marcinkubica** [comment]
Hi @dsommers 

Since you decided to just close https://github.com/OpenVPN/openvpn3-linux/issues/44 I have to use this issue to respond.

I'm only here because I'm your business client looking more into the product. Thanks also to my decision your Company has new business client, with potential to grow accounts and services in some numbers.

While I appreciate your linux openvpn3 is in beta, your user experience doesn't need to be. However the level of arrogance displayed here is just stunning.

I will refrain from commenting back on your "distros" approach from the other ticket, as I now understand it will be a waste of my time. Just wanted to tell you, getting clients these days is easy, but losing them even easier. It would be good to reflect on wider effects of your actions and how you treat your users. I can only imagine there's no one in OpenVPN inc even reviewing what are you doing here, and how you respond to people, ignoring not only me, but other users trying to get you message across. In agile though, such authoritarian approach of a single user slapping cases close in the face is toxic. That's all I wanted to say. 

Take care and have nice day.

**Comment by ordex** [comment]
@marcinkubica please consider that openvpn3-linux does not have apt repos for *every* codename out there, therefore your solution wouldn't work either as somebody else would then open another ticket complaining that he gets 404 and that we'd need a table in the doc with supported releases...

This said, for support from OpenVPN, Inc. and for feedback about their products, please refer to the official support channels.
What happens here is totally and only related to the FOSS project, its logics and policies. The term "customer" does not really apply.

If you are here as open source supporter, please either provide a patch for fixing what you think is wrong or feel free to start a discussion in a constructive manner.

Stating that what somebody else has done "is just wrong" or it's "not how you do it in 2021", without providing any concrete suggestion (i.e. a patch or a rewording) does not help either.
A FOSS project maintainer simply cannot (and is not expected to) reply to every random request appearing on this or other issue trackers (and I can assure you there are many).

**Comment by marcinkubica** [comment]
Antonio, I did provide suggestion. You have aparently missed it.

**Comment by dsommers** [comment]
Sealing this one off too.  @ordex covered the crux of it, and you seem to have skipped this part of his response:

> openvpn3-linux does not have apt repos for every codename

If you are an OpenVPN Inc customer, the support channel is here: https://openvpn.net/support/
If you are using the OpenVPN Cloud service, this is the instructions you should follow https://openvpn.net/cloud-docs/installing-connector-for-linux/

This GH issues tracker is targeting community users, where there are issues in the software of this project alone.
