### ISSUE TITLE
Change pulling of codename to something sensible

### ISSUE THREAD

**Issue by marcinkubica** [OpenVPN/openvpn3-linux#44]
In your docs there are multiple errors. You are not after either distro nor releasename

![image](https://user-images.githubusercontent.com/1593987/116448232-c885e400-a850-11eb-8b7a-c9cba9229525.png)

You are after codename. Man lsb_release for more.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy

```

Replace 

```
 wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$DISTRO.list
```

with 
```
 wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$(lsb_release -sc).list
```

example echo
```
$ echo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$(lsb_release -sc).list
wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-groovy.list
```

**Comment by marcinkubica** [comment]
Hi, thanks for closing without a word of explanation.

By that your encouragement to provide feedback or support for opensource projects is amazing.

Well done.

**Comment by mattock** [comment]
I have seen the "lsb_release -sc" pattern used elsewhere so I generally agree with @marcinkubica. Al lthe Ubuntu and Debian systems (desktop, VM, etc) I've seen have LSB packages installed by default, so the lsb commands should "just work". On Red Hat derivates you typically need to install redhat-lsb-core to get it, but that's outside of the scope of this report.

**Comment by ordex** [comment]
I can confirm it works on my debian too, fresh of installation:
```
# lsb_release -sc
buster
```

**Comment by dsommers** [comment]
The thing is that the LSB approach is being replaced with os-release approaches.  I'm not putting efforts into getting this right across all distros.  And that non-Debian based distros needs to install another package is also a no-go.

Using common sense and reading documentation is something I do expect any users will do.  And that will anyhow be needed to make use of the more advanced features of OpenVPN 3 Linux anyhow.

Case closed.
