### ISSUE TITLE
Cannot install on Fedora 34

### ISSUE THREAD

**Issue by mdouglass** [OpenVPN/openvpn3-linux#45]
```
$ sudo yum install openvpn3-client
[sudo] password for user: 
Last metadata expiration check: 1:14:56 ago on Wed 28 Apr 2021 12:31:59 PM PDT.
Error: 
 Problem: conflicting requests
  - nothing provides libprotobuf.so.24()(64bit) needed by openvpn3-client-13-0.beta1.fc34.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

Looks like Fedora shipped with protobuf 3.14 which has libprotobuf.so.25, not .24.

**Comment by dsommers** [comment]
Seems like a rebuild is needed, to pick up the latest dependency changes before the final release.

**Comment by dsommers** [comment]
I've kicked off a new rebuild for F34 and Rawhide.  Thanks for reporting it.  Feel free to re-open if the issue is still persistent.

https://copr.fedorainfracloud.org/coprs/dsommers/openvpn3/build/2151786/

**Comment by mdouglass** [comment]
Thanks @dsommers!
