### ISSUE TITLE
Question: It supports ipsec connections?

### ISSUE THREAD

**Issue by RafaelAybar** [OpenVPN/openvpn3-linux#5]
I need ipsec in my vpn´s

**Comment by cron2** [comment]
Hi,

On Thu, Jan 31, 2019 at 11:37:31PM -0800, Rafael Aybar Segura wrote:
> I need ipsec in my vpn´s

Then OpenVPN is not the tool for you.  It does not support IPSEC and
never will.

Not sure why you're posting this to a *bug tracker*, though.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by RafaelAybar** [comment]
oh, why?

**Comment by dsommers** [comment]
OpenVPN and IPSec are two very different protocols which both provides a virtual private network experience.  But there are no similarities between the packets being passed on the wire between the clients and server.  Asking OpenVPN to support IPSec is like asking Microsoft to run macOS applications natively in Windows.

If you really need IPSec, then you need to look at IPSec related projects, like FreeSwan, OpenSwan, LibreSwan or whatever they are called these days .
