### ISSUE TITLE
DNS randomly doesn't pop

### ISSUE THREAD

**Issue by falcocoris** [OpenVPN/openvpn3-linux#52]
OS : Ubuntu 20.04 LTS
Openvpn version : OpenVPN 3/Linux v13_beta 

Problem : 

Randomly, the DNS isn't configured.
I run a `systemd-resolve --status` and see no DNS.
Restarting it or disconnecting and re connecting fixes the issues most of the time.
I've tried to get a number : Out of 10 disconnection / reconnection, i get the DNS 7/10 times

**Comment by dsommers** [comment]
Have you enabled the `systemd-resolved` integration, or do you use the default `/etc/resolv.conf` approach?  The latter modifies the `resolv.conf` while the former will use API's available directly in the `systemd-resolved` service.  Details on how to enable it is here: https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg20607.html

As of the coming v14_beta release, the `systemd-resolved` integration will be enabled by default on Ubuntu 20.04 and newer.

**Comment by falcocoris** [comment]
It indeed seems to fix it, thx !
