### ISSUE TITLE
openvpn3 session-start --config autoload/ config-import: ** ERROR ** ERR_PROFILE_GENERIC: cannot open for read: autoload/

### ISSUE THREAD

**Issue by joseantoniosie1** [OpenVPN/openvpn3-linux#56]
hello Sommers,

I did a fresh clean Openvpn3 installation for my Fedora34 which It went well, 

but after try to start : 
openvpn3 session-start --config autoload/

and as a result this is what it showed:
config-import: ** ERROR ** ERR_PROFILE_GENERIC: cannot open for read: autoload/

**Comment by dsommers** [comment]
What do you expect?  You seem to provide a directory, that won't work.  Do you mix this with [`openvpn3-autoload`](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-autoload.8.rst)?
