### ISSUE TITLE
v14~beta+focal cannot connect to OpenVPN cloud using SAML

### ISSUE THREAD

**Issue by ds20prefecture** [OpenVPN/openvpn3-linux#57]
Background - Ubuntu auto-update upgrades from 13 beta to 14 beta
Upgrade: openvpn3:amd64 (13~beta-1+focal, 14~beta+focal)

Issue:
Cannot connect to existing OpenVPN3 profile from OpenVPN cloud which uses SAML to O365 for auth

Error
"session-start: ** ERROR ** Failed to start new session: Failed calling D-Bus method Ready: GDBus.Error:net.openvpn.v3.sessions.error: Backend VPN process have died.  Session is no longer valid." .

Debug log:
** ERROR ** org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:net.openvpn.v3.sessions.error: Failed communicating with VPN backend: Failed calling D-Bus method Connect: GDBus.Error:net.openvpn.v3.backend.error.standard: Failed executing D-Bus call 'Connect': Failed preparing proxy: Error calling StartServiceByName for net.openvpn.v3.netcfg: Invalid configuration (missing or empty <user>?)

Roll back to 13_beta works fine.

**Comment by ordex** [comment]
Hi @ds20prefecture have you tried v15_beta?
It was released yesterday: https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg22630.html

**Comment by ds20prefecture** [comment]
> Hi @ds20prefecture have you tried v15_beta?
> It was released yesterday: https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg22630.html

Just tried and yes, it seems to work.

**Comment by ordex** [comment]
Thanks a lot for confirming!
I am closing this issue.

**Comment by ds20prefecture** [comment]
Can it be re-opened? V15 did not fix, apologies. The V13 process was still running after the change.

**Comment by dsommers** [comment]
Please provide more details what is not working.

1. Check that all services are running the expected version:

        [user@host:~]$ openvpn3-admin version --services

2. Increase the default logging before connecting:

        [root@host:~]# openvpn3-admin log-service --log-level 6

3. Retrieve system logs

        [root@host:~]# journalctl --since -30m SYSLOG_IDENTIFIER=net.openvpn.v3.log + SYSLOG_IDENTIFIER=openvpn3-service-logger + SYSLOG_IDENTIFIER=dbus + _SYSTEMD_UNIT=dbus.service + UNIT=dbus.service

**Comment by dsommers** [comment]
Re-closing as this was also filed as a new issue in issue #63
