### ISSUE TITLE
reconnect ovpn when dc or reboot

### ISSUE THREAD

**Issue by hendranata** [OpenVPN/openvpn3-linux#60]
do u have tutorial from CLI how do we auto start ovpn connect during server linux centos 7 reboot or network disconnected ?

i have read this article as well: https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux

in windows we have settings: reconnect on reboot, connection timeout..
how about in linux CLI?

thanks

**Comment by dsommers** [comment]
Currently this should be handled by [`openvpn3-autoload`](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-autoload.8.rst).

In a future release, we will add a more native systemd integration.
