### ISSUE TITLE
v15_beta autoload requires aenum, even though its already installed

### ISSUE THREAD

**Issue by msteninger** [OpenVPN/openvpn3-linux#64]
Ubuntu 16.04
Python 3.7.5
pip 21.2.1

running `openvpn3-autoload --directory .openvpn3/autoload/`
results in:
`** ERROR **  The openvpn3 module requires the aenum module on this platform.  Install via pip3.`

when I install aenum via pip/pip3
`Requirement already satisfied: aenum in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (3.1.0)`

I installed openvpn3 via apt-get, not built from source.

**Comment by dsommers** [comment]
This is odd.  But it looks like the aenum package is installed in a user directory, not system.

That said, we are retiring the Ubuntu 16.04 support - as it is now [EOL](https://help.ubuntu.com/community/EOL#Ubuntu_16.04_Xenial_Xerus).  This is not something I'm going to spend time on now.

Please upgrade to at least 18.04 or preferably 20.04.

**Comment by msteninger** [comment]
Works for me! I was just putting off the upgrade on this machine out of laziness, thanks for the response!
