### ISSUE TITLE
Storing VPN Passwords in plain text autoload file, on server. Issue?

### ISSUE THREAD

**Issue by Danrancan** [OpenVPN/openvpn3-linux#68]
I apologise in advance for the noob question and if this is in the wrong place.
I am running openvpn3 on a server, and I would feel much more comfortable if my myvpn.autoload file wasn't world readable, since it stores my vpn password in it.

I am wondering if there is either a safe way to...
1. `sudo chmod 600 myvpn.autoload` file so that only root can read it, while still still allowing openvpn to read it upon activation. Currently, openvpn3 pops up with a read error when trying to read a `chmod'd 600 `autoloaded file. `sudo chmod 644` seems to be the loweset permsissions it can go without affecting the openvpn3 startup client. The other option would be to...
2. Somehow create a one-way hashed password of the original password, so that even if the hash is stolen, users cannot log into my openvpn-as web interface. 

Would these options be a safer way to store passwords in the autoload file? If so, are any of these options possible, and could someone point me in the direction of getting started with accomplishing this?

Thanks for all of the help! Keep up the great work!

**Comment by Danrancan** [comment]
> It is a bit unclear to me how you utilize `openvpn3-autoload`.

So in my `/etc/openvpn3/autoload` directory I have `myvpn.conf` and `myvpn.autoload` files. My autoload file looks like this:
```
{
   "autostart": true,
    "name": "myvpn",
    "acl": {
        "set-owner": "my_ubuntu_username_(not_root)"
    },
    "tunnel": {
        "ipv6": "no",
        "persist": true,
        "dns-fallback": "google",
        "dns-setup-disabled": false
    },
    "user-auth": {
        "username": "myvpnusernamehere",
        "password": "myvpnpasswordhere"
    }
}
```
Then I have run `sudo chmod 644` (because `sudo chmod 600` causes errors for some reason) and` sudo chown root:root` on /etc/openvpn3/autoload/myvpn.conf and on /etc/openvpn3/autoload/myvpn.autoload. Like so...
`sudo chown root:root /etc/openvpn3/autoload/myvpn.conf`
`sudo chown root:root /etc/openvpn3/autoload/myvpn.autoload`
`sudo chmod 644 /etc/openvpn3/autoload/myvpn.conf`
`sudo chmod 644 /etc/openvpn3/autoload/myvpn.autoload`

Finally, to run my vpn I have enabled system.d auto-start with the following command:
`sudo systemctl enable openvpn3-autoload.service`

This configuration works, however, the .conf and the .autoload files are still world readable, which is the issue. Chmod 600 on those files causes an error in openvpn startup. The only thing that I can think of is in my openvpn.autoload file, should `"set-owner": "my_ubuntu_username_(not_root)"` be changed to `"set-owner": "root"`? 

I am also interested in attempting to launch openvpn3 using the mentioned `openvpn3 config-import --config $FILENAME --name $PROFILE_NAME --persistent` settings. If attempting to do so while using `sudo systemctl enable openvpn3-autoload.service` to auto-start openvpn3, how exactly would I implement that in the system.d's systemctl command? Essentially, I want my openvpn3 to be as secure as possible, which sounds like using the `openvpn3 config-import --config $FILENAME --name $PROFILE_NAME --persistent` command is the best option for this. Do you have any tips on implementing this option with the `sudo systemctl enable openvpn3-autoload.service` command? And, is there any difference (security wise) between running openvpn3 as root, or as another user? Would it be best to create a non-root user specifically for openvpn3 before importing the persistent profile that only the "openvpn3" user could read? Or does this not matter?

Sorry for the late response and relatively babbling post. I really appreciate your prompt and thorough replies. If there is anything I can do to help the cause, please let me know (I'm good at writing documentation and tutorials). 

Dan

**Comment by Danrancan** [comment]
Sorry, after re-reading the rest of your post, I found this which is what I'm looking for.
> In a coming openvpn3-linux release, we will introduce a new and better systemd integration as well, which will make use of persistent configuration profiles. This will eventually replace `openvpn3-autoload`.

My question (please forgive my lack of knowledge of systemd) would be, is there any workaround to use systemd with the persistent configuration profiles, and if not, what would the most secure way be to run openvpn at startup throught the use of systemd? One issue seems to be that  the systemd startup command cannot run without sudo (or root) privileges, so if I am right in thought, I would assume that the openvpn configuration & autoload files would be best owned by root, and run as root (the default in systemd startup?). Are my assumptions here correct, and can you add any additional information to help my better understanding of running openvpn3 using `sudo systemctl enable openvpn3-autoload.service`?

Again, thanks for all the time you put into this project, and in helping answer questions. If there is anything I can do to help, please let me know.

Dan

**Comment by dsommers** [comment]
Sorry for the late follow up.

We released v16_beta a little while back.  That does now support `systemctl {start,stop,status} openvpn3-session@CONFIGNAME.service`  (see the [`openvpn3-systemd`(8) man page](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-systemd.8.rst#example) for details).  Use credentials saved in the configuration profile should then be used automatically.

Currently only the `root` user will be able to use this feature, but we are looking into how to enable `systemctl --user` as well.  The `root` user can also manage sessions handled this way via `openvpn3 session-manage`, with systemd catching if the session is stopped and setting the status accordingly.  Future releases will also improve transferring the session ownership to a user as well, when sessions are started at boot time.

**Comment by dsommers** [comment]
Closing this, as I believe we have alternative solutions available in current releases.  If something is still missing, please reopen this ticket.
