### ISSUE TITLE
Using openvpn3 in Gitpod

### ISSUE THREAD

**Issue by 107ef363-c60f-46fb-a8bc-da8c5f4f6938** [OpenVPN/openvpn3-linux#69]
I am trying to connect to an OpenVPN server from [Gitpod](https://www.gitpod.io/). Since this client is designed to be run by unprivileged users, it seems like a great fit.

However I get this error when running `openvpn3 session-start --config ${MY_CONFIGURATION_FILE}`:
```
** ERROR ** Could not connect to the D-Bus daemon for : Could not connect: No such file or directory
```

I'm guessing I have to set up a D-Bus daemon manually to get it to work. Can anyone confirm this or correct me if it's something else?

**Comment by 107ef363-c60f-46fb-a8bc-da8c5f4f6938** [comment]
@dsommers I installed dbus-broker and `systemctl enable dbus-broker.service` seems to be working (it successfully creates the link at `/etc/systemd/system/dbus.service`). But I'm still getting the same error. 

```
** ERROR ** Could not connect to the D-Bus daemon for : Could not connect: No such file or directory
```

I'm still not sure what file exactly openvpn3-linux is looking for but clearly it's not where it is expecting it to be. Is there a way to point it to the correct location?

**Comment by dsommers** [comment]
That error is a generic error message from the kernel, where most likely the D-Bus implementation is not able to find the socket applications use to talk with the D-Bus daemon.  Can you try to use strace to see which `open()` calls fail?

**Comment by 107ef363-c60f-46fb-a8bc-da8c5f4f6938** [comment]
@dsommers These two calls seem to be responsible:

```
connect(5, {sa_family=AF_UNIX, sun_path="/var/run/dbus/system_bus_socket"}, 110) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/charset.alias", O_RDONLY) = -1 ENOENT (No such file or directory)
```

**Comment by dsommers** [comment]
That looks like dbus-broker isn't configured to run a system bus.  Or that some symlinks are missing.  This is kinda out-of-scope for openvpn3-linux itself, as openvpn3-linux expects basic D-Bus functionality to be present.  Try to use various standard d-bus tools (busctl, gdbus, d-feet, etc) to see if you can introspect system services.

**Comment by dsommers** [comment]
Closing this now, as this is not related to openvpn3-linux itself, but more a generic system issue.

**Comment by jmls** [comment]
did you ever get this working ? Hitting the same problem

**Comment by ToanLyHoa** [comment]
> I want to use it inside of a docker container. But I am running in the same issue.

Did you handle it?

**Comment by venkatamutyala** [comment]
Any workarounds to use this from docker?

**Comment by noahfraiture** [comment]
Hey, do you have any solution 4 years later ? I can't run it on my host because I have `Could not start new VPN session: New tunnel did not respond` this issue, and I can't run it a container because of `Could not connect to the D-Bus: Could not connect: No such file or directory`
