### ISSUE TITLE
Debian 11 support

### ISSUE THREAD

**Issue by bpisee** [OpenVPN/openvpn3-linux#72]
Hi Team, after upgraded my linux servers to Debian 11, found that looks like openvpn3 is still not support this released new version of Debian 11.  

and your installation links below:
https://openvpn.net/openvpn-client-for-linux/
https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux?_ga=2.198940399.1711425365.1631146552-393711666.1631146552

may i have any of your timeline for supporting this? thanks.

Kind Regards,
Lee

**Comment by dsommers** [comment]
Hi, yes we're aware of this.  We are planning to add Debian 11 support with the next v16_beta release.  Hopefully we will have that released within the next 4 weeks or so, but no firm ETA yet.

**Comment by dsommers** [comment]
v16_beta was released earlier today including Debian 11 packages.
