### ISSUE TITLE
Can't install openvpn3

### ISSUE THREAD

**Issue by razafinarivohanania** [OpenVPN/openvpn3-linux#73]
Hello, i'm on Ubuntu 20.04 and i attempt to install openvpn3 following this guide https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux but i'm blocked in last step.

`# apt install openvpn3`

It outputs :

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package openvpn3
```

Anyone can help me? Thanks in advance. :)

**Comment by dsommers** [comment]
What does your `/etc/apt/sources.list.d/openvpn3.list` file contain?

**Comment by razafinarivohanania** [comment]
@dsommers it contains this :

```
# OpenVPN 3 Linux client - Ubuntu 20.04
deb https://swupdate.openvpn.net/community/openvpn3/repos focal main
```

**Comment by dsommers** [comment]
Did you remember to run `apt update` before the `apt install` command?

**Comment by RafayAK** [comment]
I'm also facing this issue. The problem seems to stem from the `apt-key add` command:

```
~$ sudo apt-key add openvpn-repo-pkg-key.pub
gpg: invalid key resource URL '/tmp/apt-key-gpghome.P1B9WOT5A4/home:manuelschneid3r.asc.gpg'
gpg: keyblock resource '(null)': General error
gpg: key 7721F63BD38B4796: 2 signatures not checked due to missing keys
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Total number processed: 12
gpg:       skipped new keys: 12
```

As the add key does not work running running `apt update` just before installing results in the following error:
```
~$ sudo apt update
Get:1 https://swupdate.openvpn.net/community/openvpn3/repos focal InRelease [6,840 B]
Err:1 https://swupdate.openvpn.net/community/openvpn3/repos focal InRelease    
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 551180AB92C319F8
```

**Comment by dsommers** [comment]
You seem to have skipped several steps described on the wiki page, or that errors occurred which has not been resolved.  Please go through all the steps from the wiki page again.

**Comment by dsommers** [comment]
You seem to have some issues with importing the repo PGP public key.  You need to ensure the downloaded `openvpn-repo-pkg-key.pub` is a valid public PGP key and ensure that gets properly imported.

**Comment by RafayAK** [comment]
@dsommers yep, problem seemed to be at my end. 
Used this fix:
`sudo rm "/etc/apt/trusted.gpg.d/home:manuelschneid3r.gpg"`
https://askubuntu.com/questions/1246031/gpg-invalid-key-resource-url-following-docker-official-guide
from here :

**Comment by Su-HackZ** [comment]
I'm using Kali Linux and trying to download the OpenVPN3
via official https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux

I have tried all Debian releases, still it's not downloading
DISTRO=stretch
DISTRO=buster
DISTRO=bullseye
DISTRO=bionic
DISTRO=focal
DISTRO=hirsute

command: curl -fsSL https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$DISTRO.list >/etc/apt/sources.list.d/openvpn3.list

Error:
Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://swupdate.openvpn.net/community/openvpn3/repos buster InRelease' doesn't support architecture 'i386'

**Comment by dsommers** [comment]
@Su-HackZ The correct answer is in the error log: `' doesn't support architecture 'i386'`

OpenVPN 3 Linux only supports 64-bits operating systems (x86_64/amd64 and aarch64/arm64).

**Comment by Su-HackZ** [comment]
> 

Using the 64-bits operating system shown below, but the repository automatically detected architecture 'i386', how can I change that. 

 Linux neel 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux

**Comment by dsommers** [comment]
@Su-HackZ so you have a multi-arch installation.  apt will by default try to look for both 32 and 64 bit packages.  The workaround here is to change the start of the `deb` line to look like this: ` deb [arch=amd64]`.

**Comment by vladhtt** [comment]
facing the same problem 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package openvpn3


The  /etc/apt/sources.list.d/openvpn3.list  looks like : 

VirtualBox:~$ cat /etc/apt/sources.list.d/openvpn3.list
cat: /etc/apt/sources.list.d/openvpn3.list: No such file or directory

What would be the problem ?

**Comment by dsommers** [comment]
@vladhtt You have not succeeded downloading the proper repository file.  Look carefully at the output of the `curl` command line to ensure you do get contents downloaded.

**Comment by vladhtt** [comment]
and what exactly do I curl @dsommers could you suggest please ?

**Comment by dsommers** [comment]
@vladhtt RTFM https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux

**Comment by vladhtt** [comment]
@dsommers 
vlad@vlad-VirtualBox:~$ openvpn3 session-start --config ~/ovpn/prod.ovpn
Using configuration profile from file: /home/vlad/ovpn/prod.ovpn
Session path: /net/openvpn/v3/sessions/...
Auth User name: vlad.
Auth Password: 
Enter Authenticator Code: 334765
session-start: ** ERROR ** User authentication failed



There's some progress - new error.
Would you mind to share your thoughts?
Thanks David!

**Comment by dsommers** [comment]
@vladhtt Your VPN server rejected your login.  Wrong username/password/OTP token code ... AKA: User authentication failed.

**Comment by 3009aksingh** [comment]
I was facing the same problem, what I did is again performed the mentioned steps serially and was able to install openvpn3 successfull on Ubuntu 20.04 LTS.

**Comment by pragnesh-singh-rajput** [comment]
cmd :- sudo apt install openvpn3

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 openvpn3 : Depends: libprotobuf23 (>= 3.12.4) but it is not installable
            Recommends: kmod-ovpn-dco (< 0.2) but it is not installable
Error: Unable to correct problems, you have held broken packages.

**Comment by dsommers** [comment]
@pragnesh-singh-rajput Please read the installation instructions carefully  and ensure you enable the proper apt repository.  You seem to have chosen the wrong one for your distribution version.
