### ISSUE TITLE
Raspberry pi support, unable to locate package. Is raspbian supported?

### ISSUE THREAD

**Issue by winkelermatthias** [OpenVPN/openvpn3-linux#79]
No instructions on Openvpn Cloud and Raspberry Pi to be found. the openvpn (older client) does not accept the .ovpn file from the openvpn cloud. So I assume Openvpn3 is required for Openvpn Cloud but support for Raspberry Pi is not seen in the selection menu under linux.

**Comment by dsommers** [comment]
This is related to issue #49.  Currently we only support 64-bit distributions with OpenVPN 3 Linux.
Please contact the [OpenVPN Support](https://openvpn.net/support/) in regards to why OpenVPN 2.x does not work.  OpenVPN Cloud should work with OpenVPN 2.4 and newer.

Closing this issue, as further progress in supporting 32-bit distributions is handled in issue #49, and this is not a proper support channel for OpenVPN 2.x.
