### ISSUE TITLE
Can't get autoload to work with openvpn cloud profile.

### ISSUE THREAD

**Issue by F1reP0wer12345** [OpenVPN/openvpn3-linux#87]
### The goal:
I think the title is self explanatory. I can't figure out how to get the username and password comabination, stored in a file, used by openvpn3 linux, to connect to a openvpn cloud account.

### What I'm currently using:
I'm using a linux machine to get the openvpn3 linux client to connect using the folowing files:
config.autoload:
```
{
    "autostart": true,
    "user-auth": {
        "autologin": true,
        "username": "myusername",
        "password": "mypassword"
    }
}
```
config.ovpn (generated using the download profile button next in the devices tab on username.openvpn.com/users):
```
setenv USERNAME "t**********x/f********/4*******-2***-3***-8***-f***********"
# OVPN_WEBAUTH_FRIENDLY_USERNAME=t**********x/f********/d*****_1
# OVPN_FRIENDLY_PROFILE_NAME=f********@t**********x.openvpn.com [*********]
client
dev tun
remote ******************************
remote ******************************
remote *****************************
remote ******************************
remote ******************************
remote ******************************
remote ******************************
remote ******************************
remote-cert-tls server
cipher AES-256-CBC
auth SHA256
persist-tun
nobind
verb 3
socket-flags TCP_NODELAY

<ca>
-----BEGIN CERTIFICATE-----
*****************************************************************
-----END CERTIFICATE-----
</ca>

<cert>
-----BEGIN CERTIFICATE-----
*****************************************************************
-----END CERTIFICATE-----
</cert>

<key>
-----BEGIN RSA PRIVATE KEY-----
********************************************************
-----END RSA PRIVATE KEY-----
</key>

key-direction 1
<tls-auth>
-----BEGIN OpenVPN Static key V1-----
*******************************
-----END OpenVPN Static key V1-----
</tls-auth>
```

### What I've tried (and didn't work):
0. Searching on google and finding discussions about the old openvpn v2
1. Edit the ovpn profile with the old `auth-user-pass file.txt` line.
2. Created a .autoload file. (linked above) Ran it using the command provided by: [https://openvpn.net/blog/openvpn-3-linux-and-auth-user-pass/#:~:text=sbin/openvpn3%2Dautoload%20%2D%2D-,directory,-%24HOME/.openvpn3/autoload](https://openvpn.net/blog/openvpn-3-linux-and-auth-user-pass/#:~:text=sbin/openvpn3%2Dautoload%20%2D%2D-,directory,-%24HOME/.openvpn3/autoload)
3. Tried a supposedly working file for a custom server (not openvpn cloud) from a discussion. Modified it to point to the right server.
4. Tried adding some lines from the above config.ovpn to improve the new ovpn.
5. Removed the new ovpn and started using the old config.ovpn (again provided above)

And now I'm here. Asking what I'm supposed to do now. I know this might not be the right place to ask this, but it's one of the first time i'm asking on forums and such. If anyone knows how to save the password (and of course the username) so i don't have to enter it at every reboot, that would be greatly appreciated.

**Comment by F1reP0wer12345** [comment]
I've just found a temporary solution, which, to be hones, isn't perfect. After signing in to my openvpn cloud once, I can save the password in the default browser firefox. If I ever need to reboot again, i just run the command to connect, click the saved login details, and login. Still, this is very inefficient, and can be made so much easier if i just get the autoload function working, If you have any suggestions, please post them.

**Comment by dsommers** [comment]
Instead of user/password based authentication, the profile should be created as a host profile instead.  This way you can use the `openvpn-connector-setup` utility which will do all the setup correctly on your host.  VPN profiles in OpenVPN Cloud targeted for end-users are not suitable for the `openvpn3-autoload` approach.

For more details: https://openvpn.net/cloud-docs/connector/

**Comment by F1reP0wer12345** [comment]
Thanks for the information. I'll think about this so called connector. I don't really have a system I leave on 24/7. The only purpose for me to have an OpenVPN Cloud account was mainly to get access to programs that operate locally (for example spacedesk) to work outside my local network. The VPN was there to skip the need of port forwarding on routers. Sorry for my bad english. I hope it all makes sense.

**Comment by dsommers** [comment]
Host profiles should be functional for that use case as well.  There is nothing expecting a connector to be online 24/7. And using the host based connector setup allows you to avoid username/password auth.  A user profile is targeted for users actively authenticating themselves.

**Comment by dsommers** [comment]
Closing this as I still believe using a host profile is a much better approach for this use case.
