### ISSUE TITLE
It didn't like my .ovpn config file

### ISSUE THREAD

**Issue by pstephenwille** [OpenVPN/openvpn3-linux#9]
Should I expect it to work with my current openvpn config file?
Tried
`openvpn3 session-start --config my-current-connection.ovpn`

**Comment by dsommers** [comment]
Yes, but you don't provide any details to explain why it didn't work - like errors messages or what is in the logs (`journalctl -u dbus --since today`, look for openvpn3 messages).  You might also get more details if you run it via `openvpn2 --config my-current-connection.ovpn --verb 6`.

**Comment by pstephenwille** [comment]
Not sure what was wrong my .ovpn file but it was created from the AWS VPN-Client service and windows also choked on it.  Using a file created by OpenVPN AccessServer worked fine on nix, win, and mac.

**Comment by dsommers** [comment]
If you can try the failing configuration with `openvpn2`, that would be helpful.  That would hopefully give some clues.  If you could provide a sanitized configuration file (mangled keys, certs, usernames, etc), that could also help.

**Comment by dsommers** [comment]
Closing as the issue seems to be resolved.
