### ISSUE TITLE
Latest update leaves me stucked in Connecting...

### ISSUE THREAD

**Issue by ramiroGuzmanKarvi** [OpenVPN/openvpn3-linux#94]
I'm currently running Ubuntu 20.04.03 LTS.
Today I got the prompt to update the system and several packages, between them there was OpenVPN3 Linux Client.
After the installation succeeded, my VPN connection stopped working, tried everything: from restarting pc to completely purging openvpn and doing a clean install, could not solve the issue, now it's always stucked on Connecting.
This happened to a couple of coworkers as well. 

I managed to fix it because I had a backup of the system just before the upgrade (my coworkers weren't that lucky), so I'm sure that the upgrade was the cause of the VPN stopping working.

Any ideas or recommendations?

**Comment by fleischie** [comment]
I am running OpenVPN3 on Arch Linux as well, and I noticed the same issue when upgrading from beta_16 to beta_17.

A downgrade to beta_16 fixes the issue.


I have a log using `journalctl -f` while connecting via OpenVPN using the same config I mentioned in #90 I can send it to you if you want .. (I wasn't sure whether I should upload it to a generic pastebin or send it to you unsolicited).

:v:

**Comment by ramiroGuzmanKarvi** [comment]
We also managed to patch it using openvpn instead of openvpn3 for now, downgrading seems better tho. Thanks.

**Comment by schwabe** [comment]
A log would be good indeed

**Comment by lucasR23** [comment]
I am currently experiencing the same issue:
- openvpn version:
```
OpenVPN 3/Linux v17_beta (openvpn3)
OpenVPN core 3.git:HEAD:7765540e linux x86_64 64-bit
Copyright (C) 2012-2020 OpenVPN Inc. All rights reserved.
```
- Ubuntu: Ubuntu 21.10

I am not so experienced with openvpn3 so I am not sure where can I get the logs but if I run `openvpn3 log --session-path {PATH}` I get this:
```
2021-12-28 11:43:13 Client INFO: Connecting
2021-12-28 11:43:13 >> Connection, Client connecting
2021-12-28 11:43:16 Client INFO: Connecting
2021-12-28 11:43:16 >> Connection, Client connecting
```

**Comment by fleischie** [comment]
@schwabe I have just send an email with two log files procured using `journalctl` while attempting to login to my work VPN. One with the `verbose` output option set.

If you need additional or different info, feel free to let me know.

Thank you for your effort.

:v:

**Comment by schwabe** [comment]
not sure where you sent them, I haven't gotten any

**Comment by fleischie** [comment]
Ehm 🤔 ...
Your first name at this project, as was posted in some of the source files.

I can also send this to the one you posted in your profile?

**Comment by schwabe** [comment]
Will double check but one question ahead. Did you increase the loglevel?

    [root@host:~]# openvpn3-admin log-service --log-level 6

**Comment by dsommers** [comment]
Could this be related to issue #91?

**Comment by fleischie** [comment]
@schwabe Next time I am on my machine I will check, and send another mail if I forgot to.
@dsommers I don't get any specific error message. It doesn't necessarily print anything else. Only via journalctl, and then only the same "Connecting" one on loop.

**Comment by dsommers** [comment]
@fleischie Your logs has too low verbosity.  The `openvpn3-admin log-service` command recommended is one important step.  The try to start your configuration file via the `openvpn2` command line (also part of this project) and have `--verb 6` as the last argument.  Or have your configuration file contain `verb 6`.  The v17_beta release does some changes to the default log-levels of client sessions.

From the [release notes](https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg23422.html) (git tag [notes](https://github.com/OpenVPN/openvpn3-linux/tags), expand the v17_beta tag to see it):

* Enhancement: Log level improvements on client log data

  In prior releases, the default log level in the backend process
  was set to `6`, which is a debug level.  With this release, the
  default log level is `3`.  But this is now more easily configurable.

  - The OpenVPN 3 VPN Client process now parses and respects the
    `--verb` option.

  - The configuration profile can set a `log-level` override. 
  
  - Running VPN sessions can be adjusted on-the-fly using the
    the new `--log-level` option in `openvpn3 session-manage`.
    Changes using this approach are instant.

  - The default log level can also be changed by editing
    `/usr/share/dbus-1/system-services/net.openvpn.v3.backends.service`.
    Add the `--client-log-level 6` to the program in the `Exec=` line to
    restore the previous default log level.

**Comment by schwabe** [comment]
@fleischie found the log but your loglevel should be increased: 
`    _CMDLINE=/usr/libexec/openvpn3-linux/openvpn3-service-logger --service --state-dir /var/lib/openvpn3 --log-level 4 --syslog`

**Comment by dsommers** [comment]
Just to clarify a detail ... the command line spotted here might not be the real log-level the service is running with.  The real log level is best confirmed by running `openvpn3-admin log-service`.  An example:
```
# openvpn3-admin log-service 
 Attached log subscriptions: 5
             Log timestamps: enabled
          Log D-Bus details: disabled
          Current log level: 6
```

But more importantly, ensure the VPN session also runs with log level 6:
``` 
# openvpn3 session-manage --interface tun0 --log-level
Current log level: 6
```
(My tunnel is here using the `tun0` interface.  The `--interface` option can be exchanged with `--config` and provide the config name of the session).

To change the log level of a running session, here moving from log level 3 to 6:
```
# openvpn3 session-manage --interface tun0 --log-level=6
Current log level: 3
New log level: 6
```

**Comment by fleischie** [comment]
Hello again,

responding to your email, I tried the steps you described:
1. install `openvpn3` from the latest master,
2. import the config using `openvpn3 config-import <path> --persistent`,
3. enable legacy algorithms `openvpn3 config-manage --config <name> --enable-legacy-algorithms --show`,
4. start the VPN session `openvpn3 session-start --config <name>`.

And it seems to work.

Although I redid all this because I was first running an older version (beta_17) and there the `--enable-legacy-alrgorithms` option wasn't available.

Anyway, so I guess it is ultimately due to #91. Maybe this needs to be more explicitly communicated, otherwise I could imagine a lot more issues being opened. (Because I only use the config file that was given to me by our IT department. I don't know whether I can just change the config to use other/non-legacy ciphers and/or auth values.)

Will have to discuss with our IT department.

Thank your for debugging this issue. :v:

**Comment by schwabe** [comment]
If your server has recent enough OpenVPN version (newer than 2.4.0 released 5 years ago), you have to explicitly configure it to *not* offer the AEAD algorithms.

**Comment by dsommers** [comment]
> Maybe this needs to be more explicitly communicated, otherwise I could imagine a lot more issues being opened.

Yeah, I understand that ... but it's already listed as the first bullet point in the release notes.  Not sure what else we can do than that to highlight such issues.  But perhaps a separate FAQ will be needed in the longer run.

**Comment by fleischie** [comment]
I don't necessarily disagree, but I just had the following thoughts while reading your last message:

- As a user I would expect a situation like this - that leads to no valid connection - to be printed as a warning or error and the connection attempt to be aborted, without the need to configure the verbosity level and looking for a specific entry.
- As a developer I expect users to not have read any of the relevant informations.

I personally am glad and thankful, that you helped me with my issue. 🙇

**Comment by dsommers** [comment]
We have had a quick internal discussion, and we will look into how some of these messages are handled inside the Core library.  The Core library itself is fairly primitive in regards to logging and certain connection errors should probably use a different interface to provide connection error details. Currently, most of them are only passed via the debug log events.
