### ISSUE TITLE
Captcha on sws.openvpn domain prevents apt update

### ISSUE THREAD

**Issue by AymericFabian** [OpenVPN/openvpn3-linux#98]
Hi there,

I am trying to install the OpenVPN3 client from this webpage https://openvpn.net/cloud-docs/openvpn- ... for-linux/
In the Installation for Debian and Ubuntu section, every call to the https://swupdate.openvpn.net domain generates a captcha which prevents the wget (or curl) command from getting through.

After downloading through a browser (and validating the captchas), i can't execute sudo apt update since the sws.openvpn repo generates a captcha.

Is there a way around this ?

Thanks in advance & have a good day !

**Comment by dsommers** [comment]
It is unclear to me why you get captcha on the swupdate.openvpn.net URLs.

Which public IP address are your host using?  swupdate.openvpn.net is behind a Cloudflare setup, it could be that IP address is triggering something which results in a captcha.

**Comment by AymericFabian** [comment]
The developper is requesting data through apt update from Morocco in their office. They did use another vpn as a workaround to download the package from the repo. The issue remains though for other users.

**Comment by Johnouser** [comment]
Hey AymericFabian, lets check this one and bring this to our support channel. https://support.openvpn.com/hc/en-us/requests/new. And from your case summary, please specify the public IP your using when you encounter this issue together with Date and time (with timezone). Looking forward for your response.

**Comment by dsommers** [comment]
FYI, @AymericFabian : The web portal pointed at is the official OpenVPN Inc Support portal, available for all OpenVPN Cloud and Access Server users.  @Johnouser is part of the support team there.

**Comment by mattock** [comment]
It is definitely Cloudflare that is creating the captcha. I do not know the configuration / logic of it, but it could be triggered by some GeoIP information, the site being under attack or other things. In any case escalating this to official support makes sense.

**Comment by AymericFabian** [comment]
@Johnouser Mario San Diego (OpenVPN) from your support team doesn't want to hear anything about this thread. I opened request 402224 and Mario told me twice to go ask somewhere else.

**Comment by dsommers** [comment]
@AymericFabian There must be some internal misunderstanding here.  I'll follow this up internally.

**Comment by Johnouser** [comment]
@AymericFabian , I take over the ticket and responded to you. thanks for attaching here the ticket number so that I could follow. Looking forward for your response.

**Comment by dsommers** [comment]
Since this is the issue with swupdate.openvpn.net which is a server outside the control of this project, I'm closing this ticket now.  Further follow-ups should happen via the OpenVPN Cloud support portal.
